// Hubbub word lists of the 2026-10-06 content fixes, shared by hubbub.mjs and hub-minimum.mjs.
import { dec } from './lib.mjs';

export const HUB_REMOVE = new Set(dec(['Qk9OREFHRQ==', 'Qk9ORVI=', 'RE9ORw==', 'SE9NTw==', 'SE9STlk=', 'TFVCRQ==', 'UEVSVkVSVA==', 'UEVSVkVSVEVE', 'UElNUA==', 'UVVFRVI=', 'UkVUQVJERUQ=', 'VklCUkFUT1I=', 'Q1JBUA==', 'VFVSRA==', 'Qk9ORw=='])); // base64: never written in plain text
export const HUB_DEMOTE = new Set([...`
  ANALOGUE BLOODY CENTENARY COOKERY DAFT PONG WEIR ADVERT GIRO HOOVER METRE NETBALL PENCE PUNTER TELLY TONNE TORY
  AXIAL BABA BERG CANT CHIT COCO CORTICAL DRAPER FREEMAN GENERA GRANGE GREENWOOD INTRA MEDIAL NEURO PAVER PEPTIDE PLANAR
  PROTO RUFF UNITARY UTERINE AMIR ANIL ANON CONN CORTADO EPITHELIAL GAGE GRANGER HARPER HEPATIC HOVE INVARIANT KERN LING
  MERCER MULLER NEURONAL PARA PARR PHENOTYPE PLAT POLLARD TING TUNG UNDERWOOD WELLER
  ATLANTIC BACH BATMAN JETER TRIPOLI YORK CANTON CONTRA DADA EBOLA LAMA TORAH APACHE CAYMAN CREE IRONMAN JUNE LEVANT
  MAHATMA MING NAPA LOCH LOCO IDIOT DULLARD`.trim().split(/\s+/),
  // Mildly crude / sensitive words (base64, like every flagged word in these scripts).
  ...dec(['Qk9PVFk=', 'QlVUVA==', 'Q09DQQ==', 'Q09LRQ==', 'RElBUlJIRUE=', 'RE9QRQ==', 'R0VOVElMRQ==', 'R0hFVFRP', 'SEVBVEhFTg==', 'SEVMTA==', 'S0lOSw==', 'TU9ST04=', 'UEVFRA==', 'UE9PUA==', 'REFNTkVE', 'TlVERQ==']),
]);
