#!/usr/bin/env python3
"""Ship the 2.8 UI art sets x3 (FRIDAY-QUEUE items 9d/9c/12/22/31/23): pocket, tutorial, lobby, toasts, icons.
  pocket/out/<n>.png   -> art-pocket-<n>     tutorial/out/<n>.png -> art-tut-<n>     lobby/out/lobby-<n>.png -> art-lobby-<n>
  toasts/out/toast-<n> -> art-toast-<n>      icons/out/<n>.png    -> art-fam-ic-<n>
Web apps/web/public/art/<name>.webp - Android res/drawable-nodpi/<name_>.webp - iOS Assets.xcassets/<name>.imageset PNG.
Also writes apps/web/lib/ui-art-28.generated.ts (real pixel sizes, spread into ART_SIZE). Re-runnable."""
import json
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
WEB = os.path.join(REPO, 'apps', 'web', 'public', 'art')
IOS = os.path.join(REPO, 'apps', 'ios', 'Wordocious', 'Resources', 'Assets.xcassets')
DROID = os.path.join(REPO, 'apps', 'android', 'app', 'src', 'main', 'res', 'drawable-nodpi')
SKIP = {'contact-sheet', 'info'}   # info.png is a 61 px sliver (the family keeps art-fam-cic-info)
SETS = [('pocket', 'art-pocket-', ''), ('tutorial', 'art-tut-', ''), ('lobby', 'art-lobby-', 'lobby-'),
        ('toasts', 'art-toast-', 'toast-'), ('icons', 'art-fam-ic-', ''),
        # wave4/stats-profiles (items 16/17/20): stat icons, medals + shelf + friendship badge, Go Pro scenes.
        # These sets keep their art in the set folder itself (icons/stats/stat-bolt.png), gopro in gopro/out.
        ('icons/stats', 'art-stat-', 'stat-'), ('icons/medals', 'art-pf-', ''), ('gopro', 'art-', '')]


def ship(name, im):
    im.save(os.path.join(WEB, f'{name}.webp'), 'WEBP', quality=94, method=6)
    im.save(os.path.join(DROID, name.replace('-', '_') + '.webp'), 'WEBP', quality=94, method=6)
    iset = os.path.join(IOS, f'{name}.imageset')
    os.makedirs(iset, exist_ok=True)
    im.save(os.path.join(iset, f'{name}.png'), optimize=True)
    with open(os.path.join(iset, 'Contents.json'), 'w') as fh:
        json.dump({'images': [{'filename': f'{name}.png', 'idiom': 'universal'}], 'info': {'author': 'xcode', 'version': 1}}, fh, indent=2)


sizes = {}
for folder, prefix, strip in SETS:
    d = os.path.join(HERE, folder) if folder.startswith('icons/') else os.path.join(HERE, folder, 'out')
    for f in sorted(os.listdir(d)):
        base = f[:-4]
        if not f.endswith('.png') or base in SKIP:
            continue
        key = base[len(strip):] if strip and base.startswith(strip) else base
        name = prefix + key
        im = Image.open(os.path.join(d, f)).convert('RGBA')
        ship(name, im)
        sizes[name] = [im.width, im.height]

out = os.path.join(REPO, 'apps', 'web', 'lib', 'ui-art-28.generated.ts')
with open(out, 'w') as fh:
    fh.write("// Generated by docs/design/brand/2.8/ship-ui-28.py: the 2.8 pocket / tutorial / lobby / toast / icon art and its real\n")
    fh.write("// pixel sizes. Spread into ART_SIZE (art.ts).\n")
    fh.write("export type UiArt28Name = `art-pocket-${string}` | `art-tut-${string}` | `art-lobby-${string}` | `art-toast-${string}`\n")
    fh.write("  | 'art-fam-ic-share' | 'art-fam-ic-copy' | 'art-fam-ic-more' | 'art-fam-ic-plus' | 'art-fam-ic-minus' | 'art-fam-ic-link'\n")
    fh.write("  | 'art-fam-ic-trash' | 'art-fam-ic-bell' | 'art-fam-ic-search' | 'art-fam-ic-lock' | 'art-fam-ic-heart'\n")
    fh.write("  | `art-stat-${string}` | `art-pf-${string}` | `art-pro-${string}`;\n\n")
    fh.write("export const UI_ART_28_SIZE: Record<string, readonly [number, number]> = {\n")
    for k, (w, h) in sizes.items():
        fh.write(f"  '{k}': [{w}, {h}],\n")
    fh.write("};\n")
print('shipped', len(sizes), '->', out)
