package com.wordocious.core

// GENERATED by scripts/build-bubble-atlas.py from docs/design/brand/2.8/glyphs/out/atlas.json — do not edit.
// Per-glyph metrics in CAP-HEIGHT units: w, h, baseline-from-top, align (0 baseline, 1 comma, 2 top, 3 mid).
class BubbleGlyphMetric(val w: Double, val h: Double, val b: Double, val a: Int)

object BubbleAtlasMetrics {
    const val CAP_PX = 140
    const val GAP = -0.045
    const val SPACE = 0.38
    const val ASC = 1.0482
    const val DESC = 0.2142
    const val RIM_HEX = 0xFFF0C878.toInt()
    const val K_A = 1.1
    const val K_W = 0.9
    const val K_R = 1.4
    val glyphs: Map<String, BubbleGlyphMetric> = mapOf(
        "0" to BubbleGlyphMetric(1.0413, 1.0229, 1.0161, 0),
        "1" to BubbleGlyphMetric(0.6651, 1.0229, 1.0161, 0),
        "2" to BubbleGlyphMetric(0.922, 1.0229, 1.0344, 0),
        "3" to BubbleGlyphMetric(0.8991, 1.0413, 1.0436, 0),
        "4" to BubbleGlyphMetric(1.0046, 1.0459, 1.039, 0),
        "5" to BubbleGlyphMetric(0.9037, 1.0505, 1.0482, 0),
        "6" to BubbleGlyphMetric(0.9541, 1.0183, 1.0183, 0),
        "7" to BubbleGlyphMetric(0.8807, 0.9908, 1.0046, 0),
        "8" to BubbleGlyphMetric(0.9587, 1.0229, 1.0229, 0),
        "9" to BubbleGlyphMetric(0.9495, 1.0229, 1.0229, 0),
        "a" to BubbleGlyphMetric(0.945, 1.0, 1.0064, 0),
        "amp" to BubbleGlyphMetric(0.8945, 0.9083, 0.8945, 0),
        "apos" to BubbleGlyphMetric(0.4541, 0.5, 0.7436, 2),
        "b" to BubbleGlyphMetric(0.8624, 1.0183, 1.0142, 0),
        "c" to BubbleGlyphMetric(0.8853, 1.0183, 1.0106, 0),
        "colon" to BubbleGlyphMetric(0.4266, 0.7339, 0.7229, 0),
        "comma" to BubbleGlyphMetric(0.4725, 0.5642, 0.35, 1),
        "d" to BubbleGlyphMetric(0.8991, 1.0138, 1.0142, 0),
        "dot" to BubbleGlyphMetric(0.422, 0.3945, 0.594, 3),
        "e" to BubbleGlyphMetric(0.8119, 1.0, 0.9982, 0),
        "excl" to BubbleGlyphMetric(0.4679, 1.0, 0.9849, 0),
        "f" to BubbleGlyphMetric(0.7936, 1.0046, 1.0064, 0),
        "g" to BubbleGlyphMetric(0.9358, 1.0229, 1.0142, 0),
        "h" to BubbleGlyphMetric(0.9128, 0.9908, 0.9982, 0),
        "hyphen" to BubbleGlyphMetric(0.7294, 0.3716, 0.5899, 3),
        "i" to BubbleGlyphMetric(0.5046, 1.0183, 1.0165, 0),
        "j" to BubbleGlyphMetric(0.8578, 1.0183, 1.0165, 0),
        "k" to BubbleGlyphMetric(0.9358, 0.9954, 1.0041, 0),
        "l" to BubbleGlyphMetric(0.8257, 1.0183, 1.0165, 0),
        "m" to BubbleGlyphMetric(1.078, 0.9817, 0.9876, 0),
        "n" to BubbleGlyphMetric(0.9128, 0.9954, 1.0, 0),
        "o" to BubbleGlyphMetric(1.0275, 1.0092, 1.0046, 0),
        "p" to BubbleGlyphMetric(0.8624, 1.0321, 1.0211, 0),
        "percent" to BubbleGlyphMetric(0.945, 0.8899, 0.8766, 0),
        "period" to BubbleGlyphMetric(0.4495, 0.3991, 0.3931, 0),
        "plus" to BubbleGlyphMetric(0.8807, 0.8257, 0.7638, 3),
        "q" to BubbleGlyphMetric(1.0872, 1.0734, 1.017, 0),
        "quest" to BubbleGlyphMetric(0.7844, 1.0275, 1.0119, 0),
        "r" to BubbleGlyphMetric(0.9037, 1.0, 1.0087, 0),
        "s" to BubbleGlyphMetric(0.8532, 1.0092, 1.0128, 0),
        "star" to BubbleGlyphMetric(0.945, 0.8853, 0.9376, 3),
        "t" to BubbleGlyphMetric(0.922, 1.0138, 1.0128, 0),
        "u" to BubbleGlyphMetric(0.8945, 1.0, 1.0087, 0),
        "v" to BubbleGlyphMetric(0.9174, 1.0, 1.0, 0),
        "w" to BubbleGlyphMetric(1.1743, 1.0092, 1.0087, 0),
        "x" to BubbleGlyphMetric(0.922, 1.0092, 1.0046, 0),
        "y" to BubbleGlyphMetric(0.9862, 0.9954, 1.0115, 0),
        "z" to BubbleGlyphMetric(0.9266, 1.0092, 1.0161, 0),
    )
}
