-- Social Studio seed: the first week of drafts (generated by apps/web/scripts/social-seed.mjs; idempotent).
-- Images are composed from shipped art into apps/web/public/social/seed/ (served at wordocious.com/social/seed/).
begin;
insert into public.social_posts (id, title, kind, scheduled_at, hashtags, media, link_target, created_by)
values ('5a0c1a11-0001-4c00-9000-000000000001', 'Meet the cast', 'cast', '2026-10-07 11:30:00 America/Chicago'::timestamptz, '{wordgames,puzzlegames,dailypuzzle,wordocious}'::text[], '[{"size":"portrait","src":"public","path":"/social/seed/cast-portrait.jpg","width":1080,"height":1350},{"size":"pin","src":"public","path":"/social/seed/cast-pin.jpg","width":1000,"height":1500},{"size":"landscape","src":"public","path":"/social/seed/cast-landscape.jpg","width":1600,"height":900}]'::jsonb, 'https://wordocious.com/', 'claude')
on conflict (id) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000001-instagram', 'https://wordocious.com/', 'instagram') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0001-4c00-9000-000000000001', 'instagram', 'Ten letters. Ten friends. One very wordy family.

Meet the Wordocious cast: W, O, R, D, O, C, I, O, U and S. Each one hosts a corner of the app, from the daily puzzles to VS races with friends.

Who''s your favorite? Tell us below.

Play free: link in bio.', 'p-00000001-instagram') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000001-facebook', 'https://wordocious.com/', 'facebook') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0001-4c00-9000-000000000001', 'facebook', 'Ten letters. Ten friends. One very wordy family.

Meet the Wordocious cast: W, O, R, D, O, C, I, O, U and S. Each one hosts a corner of the app, from the daily puzzles to VS races with friends. Who''s your favorite?', 'p-00000001-facebook') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000001-threads', 'https://wordocious.com/', 'threads') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0001-4c00-9000-000000000001', 'threads', 'Ten letters. Ten friends. One very wordy family.

Meet the Wordocious cast. Each one hosts a corner of the app, from the daily puzzles to VS races with friends. Who''s your favorite?', 'p-00000001-threads') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000001-pinterest', 'https://wordocious.com/', 'pinterest') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0001-4c00-9000-000000000001', 'pinterest', 'Meet the Wordocious cast: ten letter friends who host a free daily word game. Daily puzzles, VS races with friends, and a new Word of the Day every morning.', 'p-00000001-pinterest') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000001-x', 'https://wordocious.com/', 'x') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0001-4c00-9000-000000000001', 'x', 'Ten letters. Ten friends. One very wordy family.

Meet the Wordocious cast. Who''s your favorite?', 'p-00000001-x') on conflict (post_id, platform) do nothing;
insert into public.social_posts (id, title, kind, scheduled_at, hashtags, media, link_target, created_by)
values ('5a0c1a11-0002-4c00-9000-000000000002', 'Can you solve it? (from Sept. 21)', 'teaser', '2026-10-09 12:00:00 America/Chicago'::timestamptz, '{wordpuzzle,brainteaser,wordgames,wordocious}'::text[], '[{"size":"portrait","src":"public","path":"/social/seed/teaser-portrait.jpg","width":1080,"height":1350},{"size":"pin","src":"public","path":"/social/seed/teaser-pin.jpg","width":1000,"height":1500},{"size":"landscape","src":"public","path":"/social/seed/teaser-landscape.jpg","width":1600,"height":900}]'::jsonb, 'https://wordocious.com/word/2026-09-21', 'claude')
on conflict (id) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000002-instagram', 'https://wordocious.com/word/2026-09-21', 'instagram') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0002-4c00-9000-000000000002', 'instagram', 'Can you solve it?

Four letters locked in, one to go. Purple means the right letter in the right spot, gold means right letter, wrong spot.

Drop your guess in the comments. This one comes from our Word of the Day archive (Sept. 21), so no peeking!

Play today''s puzzles free: link in bio.', 'p-00000002-instagram') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000002-facebook', 'https://wordocious.com/word/2026-09-21', 'facebook') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0002-4c00-9000-000000000002', 'facebook', 'Can you solve it?

Four letters locked in, one to go. Purple means the right letter in the right spot, gold means right letter, wrong spot.

Drop your guess in the comments. The answer is in our Word of the Day archive (Sept. 21):', 'p-00000002-facebook') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000002-threads', 'https://wordocious.com/word/2026-09-21', 'threads') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0002-4c00-9000-000000000002', 'threads', 'Can you solve it? Four letters locked in, one to go.

Purple = right spot, gold = right letter, wrong spot. Guess below. The answer is in our archive:', 'p-00000002-threads') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000002-pinterest', 'https://wordocious.com/word/2026-09-21', 'pinterest') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0002-4c00-9000-000000000002', 'pinterest', 'Can you solve this word puzzle? Four letters are locked in and one is left. Purple tiles are the right letter in the right spot; gold tiles are the right letter in the wrong spot. Tap through for the answer and play free daily word games.', 'p-00000002-pinterest') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000002-x', 'https://wordocious.com/word/2026-09-21', 'x') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0002-4c00-9000-000000000002', 'x', 'Can you solve it? Four letters locked in, one to go.

Guess below. Answer:', 'p-00000002-x') on conflict (post_id, platform) do nothing;
insert into public.social_posts (id, title, kind, scheduled_at, hashtags, media, link_target, created_by)
values ('5a0c1a11-0003-4c00-9000-000000000003', 'Word of the Day: IRONY', 'wotd', '2026-10-11 09:30:00 America/Chicago'::timestamptz, '{wordoftheday,vocabulary,learnwords,wordocious}'::text[], '[{"size":"portrait","src":"public","path":"/social/seed/wotd-portrait.jpg","width":1080,"height":1350},{"size":"pin","src":"public","path":"/social/seed/wotd-pin.jpg","width":1000,"height":1500},{"size":"landscape","src":"public","path":"/social/seed/wotd-landscape.jpg","width":1600,"height":900}]'::jsonb, 'https://wordocious.com/word/2026-09-30', 'claude')
on conflict (id) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000003-instagram', 'https://wordocious.com/word/2026-09-30', 'instagram') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0003-4c00-9000-000000000003', 'instagram', 'Word of the Day: IRONY (noun)

Saying one thing and meaning the opposite, often for a laugh. Like naming the slowest turtle in the pond "Speedy."

Use it in a sentence below. Best one gets a shout-out.

A new word every morning: link in bio.', 'p-00000003-instagram') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000003-facebook', 'https://wordocious.com/word/2026-09-30', 'facebook') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0003-4c00-9000-000000000003', 'facebook', 'Word of the Day: IRONY (noun)

Saying one thing and meaning the opposite, often for a laugh. Like naming the slowest turtle in the pond "Speedy."

Use it in a sentence in the comments. A new word every morning:', 'p-00000003-facebook') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000003-threads', 'https://wordocious.com/word/2026-09-30', 'threads') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0003-4c00-9000-000000000003', 'threads', 'Word of the Day: IRONY (noun)

Saying one thing and meaning the opposite, often for a laugh. Like naming the slowest turtle in the pond "Speedy." Use it in a sentence below.', 'p-00000003-threads') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000003-pinterest', 'https://wordocious.com/word/2026-09-30', 'pinterest') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0003-4c00-9000-000000000003', 'pinterest', 'Word of the Day: IRONY (noun). Saying one thing and meaning the opposite, often for a laugh. Build your vocabulary with a new word every morning on Wordocious.', 'p-00000003-pinterest') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000003-x', 'https://wordocious.com/word/2026-09-30', 'x') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0003-4c00-9000-000000000003', 'x', 'Word of the Day: IRONY (noun)

Saying one thing and meaning the opposite, often for a laugh. Like naming the slowest turtle "Speedy."', 'p-00000003-x') on conflict (post_id, platform) do nothing;
insert into public.social_posts (id, title, kind, scheduled_at, hashtags, media, link_target, created_by)
values ('5a0c1a11-0004-4c00-9000-000000000004', 'Halloween costumes are coming', 'season', '2026-10-14 18:00:00 America/Chicago'::timestamptz, '{halloween,spookyseason,wordgames,wordocious}'::text[], '[{"size":"portrait","src":"public","path":"/social/seed/season-portrait.jpg","width":1080,"height":1350},{"size":"pin","src":"public","path":"/social/seed/season-pin.jpg","width":1000,"height":1500},{"size":"landscape","src":"public","path":"/social/seed/season-landscape.jpg","width":1600,"height":900}]'::jsonb, 'https://wordocious.com/', 'claude')
on conflict (id) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000004-instagram', 'https://wordocious.com/', 'instagram') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0004-4c00-9000-000000000004', 'instagram', 'Something spooky is stirring in Wordocious.

The whole cast is trying on costumes, and they''ll be haunting the app from October 17 through November 1. Pumpkins, bats, a ghost or two, and plenty of candy.

Which costume is your favorite?

Play free: link in bio.', 'p-00000004-instagram') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000004-facebook', 'https://wordocious.com/', 'facebook') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0004-4c00-9000-000000000004', 'facebook', 'Something spooky is stirring in Wordocious.

The whole cast is trying on costumes, and they''ll be haunting the app from October 17 through November 1. Which costume is your favorite?', 'p-00000004-facebook') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000004-threads', 'https://wordocious.com/', 'threads') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0004-4c00-9000-000000000004', 'threads', 'Something spooky is stirring in Wordocious. The cast is trying on costumes, and they''ll be in the app October 17 through November 1. Which one is your favorite?', 'p-00000004-threads') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000004-pinterest', 'https://wordocious.com/', 'pinterest') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0004-4c00-9000-000000000004', 'pinterest', 'Halloween comes to Wordocious October 17 through November 1: the whole letter cast in costume, plus pumpkins, bats and candy. Free daily word games for the spooky season.', 'p-00000004-pinterest') on conflict (post_id, platform) do nothing;
insert into public.marketing_links (slug, target, channel) values ('p-00000004-x', 'https://wordocious.com/', 'x') on conflict (slug) do nothing;
insert into public.social_post_targets (post_id, platform, caption, link_slug) values ('5a0c1a11-0004-4c00-9000-000000000004', 'x', 'Something spooky is stirring. The whole cast is trying on costumes for Oct 17 to Nov 1.

Which one is your favorite?', 'p-00000004-x') on conflict (post_id, platform) do nothing;
commit;
