// GENERATED by packages/core/scripts/gen-mode-catalog.mjs from modes.json — DO NOT EDIT.
// Run `pnpm gen:modes` to regenerate. Edit packages/core/modes.json instead.
import SwiftUI

struct GenMode: Identifiable {
    let id: String
    let dbKey: String?
    let title: String
    let shortTitle: String
    let shareLabel: String
    let desc: String
    let accentHex: String
    let glyph: String?
    let romanNumeral: String?
    let dailyEligible: Bool
    var accent: Color { Color(hexString: accentHex) ?? .purple }
}

enum ModeGen {
    static let all: [GenMode] = [
        GenMode(id: "practice", dbKey: "DUEL", title: "Classic", shortTitle: "Classic", shareLabel: "Classic", desc: "1 word, 6 tries", accentHex: "#7c3aed", glyph: "C", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "vs", dbKey: nil, title: "VS Battle", shortTitle: "VS", shareLabel: "VS Battle", desc: "Real-time PvP", accentHex: "#0d9488", glyph: nil, romanNumeral: nil, dailyEligible: false),
        GenMode(id: "quordle", dbKey: "QUORDLE", title: "QuadWord", shortTitle: "Quad", shareLabel: "QuadWord", desc: "4 words at once", accentHex: "#ec4899", glyph: "IV", romanNumeral: "IV", dailyEligible: true),
        GenMode(id: "octordle", dbKey: "OCTORDLE", title: "OctoWord", shortTitle: "Octo", shareLabel: "OctoWord", desc: "8 boards, 13 tries", accentHex: "#7e22ce", glyph: "VIII", romanNumeral: "VIII", dailyEligible: true),
        GenMode(id: "sequence", dbKey: "SEQUENCE", title: "Succession", shortTitle: "Succ.", shareLabel: "Succession", desc: "4 words, one by one", accentHex: "#2563eb", glyph: "S", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "rescue", dbKey: "RESCUE", title: "Deliverance", shortTitle: "Deliv.", shareLabel: "Deliverance", desc: "4 prefilled boards", accentHex: "#059669", glyph: "D", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "six", dbKey: "DUEL_6", title: "Six", shortTitle: "Six", shareLabel: "Classic Six", desc: "6 letters, 7 tries", accentHex: "#06b6d4", glyph: "6", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "seven", dbKey: "DUEL_7", title: "Seven", shortTitle: "Seven", shareLabel: "Classic Seven", desc: "7 letters, 8 tries", accentHex: "#84cc16", glyph: "7", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "gauntlet", dbKey: "GAUNTLET", title: "Gauntlet", shortTitle: "Gauntlet", shareLabel: "Gauntlet", desc: "5 escalating stages", accentHex: "#d97706", glyph: "G", romanNumeral: nil, dailyEligible: true),
        GenMode(id: "propernoundle", dbKey: "PROPERNOUNDLE", title: "ProperNoundle", shortTitle: "Proper", shareLabel: "ProperNoundle", desc: "Guess famous names", accentHex: "#dc2626", glyph: "P", romanNumeral: nil, dailyEligible: true),
    ]
    static func byDbKey(_ k: String) -> GenMode? { all.first { $0.dbKey == k } }
    static func byId(_ i: String) -> GenMode? { all.first { $0.id == i } }
    /// Daily modes (VS excluded), in canonical order — used by the all-dailies card.
    static var daily: [GenMode] { all.filter { $0.dailyEligible && $0.dbKey != nil } }
}
