#!/usr/bin/env python3
"""Hires queue: pack -> [(piece id, description for the one-per-image prompt)]. `python3 hires_items.py` prints the queue (pack/id: prompt)."""
Q = {
 'goth': [('bat-wing-clip','a cute bat-wing hair clip, black with purple wing membranes, silver clip'),('long-side-hair','a long straight side-swept hairstyle in neutral white-grey clay (to be tinted)'),('winged-liner-lips','bold winged eyeliner and dark purple lips as a flat face decal (eyebrows-eyes liner pair plus lips)'),('skull-bow','a black satin bow with a tiny cute skull in the middle'),('platform-boots','a pair of chunky black platform boots with silver buckles, front half'),('lace-umbrella','a closed black umbrella with lace trim and a curved handle, handle down'),('moon-pendant','a silver chain necklace with a purple crescent-moon pendant'),('bat-sunglasses','round black sunglasses with bat-wing shaped corners and purple lenses'),('black-cat-plush','a small sitting black cat plush with yellow eyes and a purple nose'),('purple-lantern','a small old lantern with a glowing purple flame')],
 'emo': [('fringe-hair','a side-swept long fringe hairstyle with two bright pink streaks, neutral white-grey clay with pink streaks'),('studded-belt','a black studded belt with a silver square buckle'),('striped-arm-warmers','a pair of black-and-white striped arm warmers'),('checker-wristbands','a pair of black-and-white checkerboard wristbands'),('skinny-tie','a skinny black-and-white striped necktie'),('star-shades','star-shaped sunglasses, black lenses with neon pink rims'),('hair-clips','a bunch of bright neon hair clips: star, lightning, heart, checker, bow'),('hoodie','a zip hoodie collar and hood, flat, neutral white-grey'),('checker-high-tops','checkerboard high-top sneakers with white laces, front half'),('pink-headphones','big black headphones with hot pink stripes'),('heart-plasters','two cute heart-shaped plasters, one pink one black'),('heart-balloon','a pink and a black heart-shaped balloon on strings')],
 'punk': [('liberty-spikes','a tall liberty-spike hairstyle with soft rounded spikes, neutral white-grey clay (to be tinted)'),('mohawk','a mohawk hairstyle, neutral white-grey clay (to be tinted)'),('studded-vest','a denim-style vest with round metal studs and cute colorful pin badges (star, heart, smiley)'),('plaid-tie-wrap','a red-and-black plaid flannel shirt tied as a wrap band'),('spike-wristband','a black wristband with silver studs and soft rubbery spikes'),('combat-boots','chunky black combat boots with hot pink laces, front half'),('studded-choker','a round black studded choker collar with soft studs and a metal ring'),('fishnet-sleeves','a pair of black fishnet arm sleeves'),('heart-shades','heart-shaped black sunglasses'),('safety-pins','a cluster of three big plastic safety pins in pink, lime and blue on a ring'),('skull-plush','a tiny cute grinning skull toy plush with a pink bow'),('studded-cap','a black leather newsboy cap with silver studs on the band')],
 'baseball': [('cap','a plain baseball cap, neutral white with a light-grey brim, no logo'),('batting-helmet','a batting helmet with an ear flap, neutral white with grey accent'),('glove','a baseball glove (mitt), tan leather with cream laces'),('bat','a wooden baseball bat, upright, with a grey tape grip'),('ball','a baseball with red stitches'),('cleats','a baseball cleat, neutral white with grey, front half'),('eye-black','two black eye-black stripes as a flat face decal'),('wristband','a white sweat wristband with a grey stripe')],
 'football': [('helmet','a plain football helmet with a face guard, neutral white and light grey, no decals'),('shoulder-pads','football shoulder pads as a flat wrap shape, neutral white and grey'),('eye-black','two black eye-black stripes as a flat face decal'),('football','a brown football with white laces and stripes'),('cleats','football cleats, neutral white with grey, front half'),('wristband','a white sweat wristband with two grey stripes'),('whistle','a coach whistle on a black cord'),('kicking-tee','a small kicking tee holding a mini football')],
 'soccer': [('ball','a classic black and white soccer ball'),('cleats','a soccer cleat, neutral white with grey studs, front half'),('shin-guards','a pair of shin guards, neutral white with grey'),('headband','a sporty headband, white with a grey stripe'),('captain-armband','a captain armband: a plain white band with a small grey star'),('goalie-gloves','a pair of goalkeeper gloves, white with grey'),('whistle','a referee-style silver whistle on a cord'),('corner-flag','a small corner flag on a pole, white and grey checks')],
 'hockey': [('helmet','an ice hockey helmet with a clear visor, neutral white with grey'),('stick','an ice hockey stick, upright, white with grey tape'),('puck','a black hockey puck'),('skates','a pair of ice skates, neutral white and grey'),('gloves','a pair of hockey gloves, white and grey'),('shoulder-pads','hockey shoulder pads as a flat wrap shape, white and grey'),('tape-roll','a roll of white hockey tape'),('beanie','a chunky knit winter beanie with a pom-pom, white with a grey stripe')],
 'basketball-golf': [('basketball','a basketball, orange with plain dark seams'),('headband','a thick white terry headband with a grey stripe'),('wristbands','a pair of white terry wristbands with grey stripes'),('high-tops','a pair of high-top basketball shoes, neutral white and grey, front half'),('jersey','a sleeveless basketball jersey as a flat wrap shape with a round neckline, neutral white with grey trim, NO number'),('mini-hoop','a small basketball hoop with a net on a short stand'),('knee-socks','a pair of knee-high athletic socks with two grey stripes'),('golf-visor','a golf visor cap, neutral white and grey'),('golf-driver','a golf driver club, upright'),('golf-ball-tee','a golf ball on a tee'),('golf-shoes','a pair of golf shoes with spikes, white and grey, front half'),('golf-glove','a white golf glove for one hand'),('golf-flag','a small golf flag on a pole in a green hole base')],
 'careers': [('safety-goggles','round clear safety goggles with a strap'),('lab-coat','a short white lab coat as a flat wrap panel, neutral white'),('flask','a bubbling green science flask'),('stethoscope','a doctor stethoscope worn as a drape'),('firefighter-helmet','a firefighter helmet in red and gold with a plain gold shield front'),('police-cap','a friendly police officer cap, blue and gold with a plain gold star badge, no weapon'),('hard-hat','a yellow builder hard hat'),('pilot-cap','a pilot cap, navy with small gold wings badge'),('aviator-shades','gold-frame aviator sunglasses'),('beret','a soft white artist beret with a little stem'),('paint-palette','an artist wooden paint palette with colorful paint blobs and a brush'),('chef-hat','a tall white chef hat'),('astronaut-helmet','an astronaut helmet with a clear dome'),('detective-cap','a brown plaid deerstalker detective cap'),('magnifier','a round magnifying glass with a gold rim and brown handle'),('safety-vest','a bright orange safety vest with reflective stripes, no text')],
 'pets': [('corgi','a cute sitting corgi puppy plush-vinyl pet, front view'),('golden-retriever','a cute sitting golden retriever puppy, front view'),('dalmatian','a cute sitting spotted dalmatian puppy, front view'),('bunny','a cute sitting white bunny with long ears, front view'),('hamster','a cute round hamster with cheek pouches, front view'),('axolotl','a cute pink axolotl with feathery gills, front view'),('mini-dragon','a cute tiny purple dragon with small wings, front view'),('mini-robot','a cute mini boxy robot with an antenna, front view'),('dino','a cute baby green dinosaur, front view'),('frog','a cute green frog sitting, front view'),('turtle','a cute small turtle with a patterned shell, front view'),('parrot','a colorful red parrot on a little perch, front view')],
 'music': [('drumsticks','a pair of crossed wooden drumsticks'),('keytar','a small red keytar (keyboard guitar) with chunky keys'),('violin-bow','a violin with its bow'),('trumpet','a shiny brass trumpet'),('dj-headphones','big purple and gold DJ over-ear headphones'),('boombox','a retro purple boombox with gold trim and two round speakers'),('note-aura','three glossy gold music notes with sparkles'),('rockstar-shades','rock-star sunglasses, black lenses with gold rims'),('glitter-mic','a glitter microphone with sparkles'),('baton','a conductor baton'),('tambourine','a red tambourine with gold jingles'),('mini-drum','a small red and white snare drum')],
 'gaming': [('controller','a game controller with two thumbsticks and four plain colored buttons, white and purple'),('headset','a gaming headset with a boom microphone, white and purple'),('pixel-shades','pixel-art sunglasses made of square black blocks with white glints'),('handheld','a handheld game console with a screen and a plus-shaped pad, purple'),('vr-goggles','chunky VR goggles with a head strap, white and black'),('arcade-token','a gold arcade token coin with a star'),('joystick','an arcade joystick with a red ball top and four gold buttons'),('pixel-heart','an 8-bit pixel heart in red')],
 'metal': [('wild-hair','a long wild hairstyle, neutral white-grey clay (to be tinted)'),('studded-jacket','a black studded leather jacket collar and shoulders, flat'),('flame-bandana','a black and red flame-pattern bandana tied as a headband'),('round-rocker-shades','round dark rocker sunglasses with silver rims'),('flame-guitar','an electric guitar in red and black with a lightning-bolt body, no logos'),('studded-cuff','a black studded leather wristband'),('fingerless-glove','a black studded fingerless glove'),('stage-boots','black stage boots with silver buckles, front half'),('pick-chain','a chunky silver chain necklace with a flame guitar-pick pendant'),('flame-amp','a small black amp speaker with a red flame sticker'),('silver-notes','glittering silver music notes with sparkles')],
 'hiphop': [('snapback','a plain snapback-style flat cap, neutral white-grey'),('bucket-hat','an oversized bucket hat, neutral white-grey'),('gold-chain-star','a chunky gold chain necklace with a plain star pendant'),('headphones-neck','big over-ear headphones, neutral white-grey'),('hoodie','an oversized hoodie collar and hood with drawstrings, flat, neutral'),('high-tops','chunky high-top sneakers, neutral white, front half'),('boombox','a retro boombox with colorful speakers'),('gold-round-shades','round gold-rim black sunglasses'),('splat-bandana','a colorful paint-splat bandana tied as a headband'),('fingerless-gloves','a pair of fingerless gloves, neutral white-grey')],
 'kpop': [('bob-hair','a sleek bob hairstyle with a bright pink streak, neutral white-grey clay'),('star-earrings','a pair of sparkly star-shaped earrings with gold studs'),('sequin-jacket','a glittering sequin stage jacket, flat'),('platform-boots','white platform boots with pink ribbon laces, front half'),('headset-mic','a headset microphone with a pink windscreen'),('heart-lightstick','a glowing heart-topped light-stick wand with a pink bow'),('heart-choker','a sparkly pink choker with a heart charm'),('round-clear-glasses','oversized round clear-lens fashion glasses with a gold frame'),('sequin-glove','a single white sequin sparkle glove'),('star-fan-flag','a star-shaped fan banner flag on a short pole, blank')],
 'cottagecore': [('straw-sunhat','a wide straw sun hat with a flower band'),('daisy-crown','a flower crown of daisies and tiny leaves'),('cream-shawl','a knitted cream shawl collar and shoulders with fringe, flat'),('picnic-basket','a wicker picnic basket with a red checkered cloth'),('mushroom-hat','a small mushroom hat, red cap with white dots'),('lace-up-boots','little brown leather boots with ribbon laces, front half'),('braid','a long braid hairstyle, neutral white-grey clay (to be tinted)'),('lantern-jar','a lantern with glowing fireflies'),('snail-buddy','a cute snail buddy with a swirly shell'),('wildflower-bunch','a bunch of wildflowers tied with twine')],
 'western': [('cowboy-hat','a cowboy hat with a plain band, neutral tan'),('dotted-bandana','a red polka-dot bandana neckerchief'),('cowboy-boots','cowboy boots with decorative stitching, front half'),('star-vest','a brown leather vest with a plain gold star badge, no text'),('lasso','a lasso rope coil'),('buckle-belt','a brown belt with a big plain oval gold buckle, flat'),('cactus-buddy','a cute smiling cactus buddy in a little pot'),('hobby-horse','a stuffed toy horse head on a stick'),('round-shades','round sunglasses with tan frames'),('tumbleweed-buddy','a cute tumbleweed buddy with a smile')],
 'surfer': [('surfboard','a surfboard standing upright with a blue wave stripe'),('shell-necklace','a puka shell necklace'),('board-shorts','white board shorts with a blue wave stripe, flat'),('rash-guard','a rash guard shirt collar and shoulders, white with blue sleeves, flat'),('floppy-sunhat','a floppy wide-brim sun hat with a blue band'),('flip-flops','a pair of white flip-flop sandals with blue straps'),('beach-hair','a sun-bleached tousled beach hairstyle, neutral white-grey clay (to be tinted)'),('mirror-shades','round gold-rim mirrored sunglasses'),('hermit-crab','a cute hermit crab buddy in a swirly shell'),('hibiscus-clip','a hibiscus flower hair clip')],
 'anime': [('spiky-hair','a tall spiky anime-style hairstyle, neutral white-grey clay (to be tinted)'),('long-ahoge-hair','a long flowing hairstyle with two antenna ahoge strands, neutral white-grey clay (to be tinted)'),('sailor-collar','a school sailor collar with a red bow, flat'),('round-glasses','oversized round gold-frame glasses with a glint'),('gem-circlet','a gold headband with a plain pink gem'),('onigiri-plush','a giant plain onigiri rice-ball plush'),('paper-fan','a folding paper fan with gold ribs, plain'),('sweatdrop-sparkles','a small set of cute sweat-drops and sparkles, flat'),('flowing-scarf','a long cream scarf flowing in the wind'),('spirit-orb','a floating cute pet spirit orb with two dot eyes')],
 'preppy': [('pleated-skirt','a pleated school-style skirt shape, flat, cream'),('sweater-vest','a cream knit sweater vest with navy trim, flat'),('bow-tie','a navy and pink striped bow tie'),('ribbon-headband','a cream headband with a big pink bow'),('loafers','a pair of brown leather loafers, front half'),('argyle-socks','a pair of argyle knee socks, navy and pink'),('satchel','a small brown leather satchel backpack'),('round-glasses','round preppy glasses with gold frame'),('polo','a cream polo shirt collar and shoulders with navy trim, flat, no logo'),('side-part-hair','a neat side-parted short hairstyle, neutral white-grey clay (to be tinted)')],
 'hippie': [('flower-headband','a flower-power headband with big daisies and beads'),('rainbow-glasses','round rainbow-tinted glasses with gold frames'),('fringe-vest','a fringe suede vest, tan, flat'),('tie-dye-bandana','a tie-dye bandana in rainbow swirls'),('bead-necklace','a necklace of colorful wooden beads and daisies'),('bell-bottoms','bell-bottom jeans with flower patches, flat'),('flower-hair','a long flowing center-parted hairstyle with a flower, neutral white-grey clay (to be tinted)'),('flower-guitar','a small acoustic guitar with flower stickers'),('tassel-bag','a woven shoulder bag with tassels'),('flower-sandals','tan sandals with daisy straps, front half')],
 'steampunk': [('goggle-top-hat','a top hat with brass goggles and gears on the band'),('brass-goggles','brass aviator goggles on a leather strap'),('gear-shoulders','a brass gear-and-cog shoulder piece, flat'),('corset-vest','a leather and cream corset-style vest with brass buttons, flat'),('key-necklace','a small clockwork key necklace on a chain'),('brass-boots','knee-high leather boots with brass buckles, front half'),('brass-robot','a tiny brass robot buddy with a key on its back'),('pocket-watch','a brass pocket watch on a chain'),('brass-wings','a pair of brass mechanical wings, small'),('steam-backpack','a little steam-pipe backpack with gauges')],
 'cyber': [('visor','a sleek visor with a glowing cyan lens'),('glow-hood-cloak','a black techwear hooded cloak collar and shoulders with glowing seams, flat'),('neck-ring','a glowing cyan neck ring collar'),('neon-boots','chunky black cyber boots with neon soles, front half'),('led-headphones','holographic LED headphones'),('circuit-armband','a glowing circuit-pattern armband'),('hover-drone','a floating hover-drone buddy with one round cyan eye lens'),('utility-bag','a futuristic black cross-body utility bag with neon accents'),('fiber-optic-hair','two fiber-optic LED hair strands with glowing tips'),('neon-cat-ears','a black headband with glowing neon cat ears')],
 'raver': [('neon-star-shades','glowing neon-rim star sunglasses'),('fluffy-legwarmers','a pair of fluffy neon-pink leg warmers'),('bead-bracelets','a stack of glowing rainbow bead bracelets'),('glowstick-crown','a glow-stick crown with stars'),('holo-bucket-hat','a holographic iridescent bucket hat'),('neon-platforms','platform sneakers with neon rainbow soles, front half'),('led-jacket','a glowing LED-wire cropped jacket, flat'),('pompom-backpack','a big fluffy pastel rainbow pom-pom backpack'),('fluffy-cat-headphones','fluffy neon cat-ear headphones'),('glitter-orb-buddy','a floating glitter-orb planet light buddy')],
 'athleisure': [('track-jacket','a zip-up track jacket collar and shoulders, white with grey panels, flat'),('joggers','a pair of jogger pants, white with grey stripes, flat'),('ponytail','a sporty high ponytail hairstyle with a scrunchie, neutral white-grey clay (to be tinted)'),('running-visor','a sleek running visor, white with grey'),('running-shoes','a pair of running shoes, white and grey, front half'),('water-bottle','a sports water bottle, white with grey'),('yoga-mat','a rolled-up yoga mat with a strap, grey-lavender'),('earbuds','wireless earbuds in a little open white case'),('fitness-band','a fitness-tracker wristband, white with a black screen'),('gym-duffel','a gym duffel bag, white and grey')],
}
TEMPLATE = ("ONE single item in this image (not a sheet). Square 1:1, same glossy 3D toy style as the reference, lit from the top-left, the item centered and filling about 85 percent of the image, "
            "on ONE flat solid cyan #00FFFF background edge to edge, no gradient, no shadow, no floor, NO text, logos or brands. Item: {d}.")
if __name__ == '__main__':
    n = 0
    for p, items in Q.items():
        for i, d in items:
            n += 1; print(f'{p}/{i}: {d}')
    print(n)
