#!/usr/bin/env python3
"""Mascot-maker item packs (FRIDAY-QUEUE 5b / 51): pack -> grid + [(piece id, slot, colorable parts)].
Slots follow INTEGRATION.md layers: head (hat/hair on top), hair, face (decals + glasses), neck (drape/necklace/scarf), wrap (worn on the
body: straps, belts, cloaks front), back (behind the body), held (in the hand), feet, pet (buddy beside the feet), extra.
Colorable = neutral white/grey clay that the code tints (hair/clothing/team color); 'no' = fixed colors."""
PACKS = {
 'goth': (4, 3, [('lace-choker','neck','no'),('velvet-cape','wrap+back','no (purple lining)'),('bat-wing-clip','head','no'),('long-side-hair','hair','hair color'),('winged-liner-lips','face','no'),('skull-bow','head','no'),('platform-boots','feet','no'),('lace-umbrella','held','no'),('moon-pendant','neck','no'),('bat-sunglasses','face','no'),('black-cat-plush','pet','no'),('purple-lantern','held','no')]),
 'skater': (4, 3, [('skateboard','held','no (wheels, deck)'),('skate-helmet','head','body = team/primary color'),('flat-brim-cap','head','primary'),('bucket-hat','head','primary'),('skate-shoes','feet','primary'),('zip-hoodie','wrap','primary'),('wrist-guards','wrap','primary'),('sweatband','head','primary'),('wayfarer-shades','face','no'),('headphones','head','primary'),('star-stickers','extra','no'),('messenger-bag','back','primary')]),
 'kawaii': (4, 3, [('bunny-ear-band','head','primary'),('cat-ear-band','head','primary'),('giant-bow','head','primary'),('twin-tails','hair','hair color'),('star-glasses','face','no'),('blush-stickers','face','no'),('rainbow-scarf','neck','no'),('platform-sneakers','feet','primary'),('heart-backpack','back','primary'),('star-wand','held','no'),('teddy-buddy','pet','no'),('strawberry-hat','head','primary (leaf fixed)')]),
 'music': (4, 3, [('drumsticks','held','no'),('keytar','held','no'),('violin-bow','held','no'),('trumpet','held','no'),('dj-headphones','head','no'),('boombox','held','no'),('note-aura','extra','no'),('rockstar-shades','face','no'),('glitter-mic','held','no'),('baton','held','no'),('tambourine','held','no'),('mini-drum','held','no')]),
 'gaming': (4, 2, [('controller','held','no'),('headset','head','no'),('pixel-shades','face','no'),('handheld','held','no'),('vr-goggles','face','no'),('arcade-token','extra','no'),('joystick','held','no'),('pixel-heart','pet','no')]),
 'baseball': (4, 2, [('cap','head','team color'),('batting-helmet','head','team color'),('glove','held','no'),('bat','held','no'),('ball','held','no'),('cleats','feet','team color'),('eye-black','face','no'),('wristband','wrap','team color')]),
 'soccer': (4, 2, [('ball','held','no'),('cleats','feet','team color'),('shin-guards','feet','team color'),('headband','head','team color'),('captain-armband','wrap','team color'),('goalie-gloves','held','team color'),('whistle','neck','no'),('corner-flag','held','team color')]),
 'emo': (4, 3, [('fringe-hair','hair','hair color'),('studded-belt','wrap','no'),('striped-arm-warmers','wrap','no'),('checker-wristbands','wrap','no'),('skinny-tie','neck','no'),('star-shades','face','no'),('hair-clips','head','no'),('hoodie','wrap','primary'),('checker-high-tops','feet','no'),('pink-headphones','head','no'),('heart-plasters','face','no'),('heart-balloon','held','no')]),
 'football': (4, 2, [('helmet','head','team color'),('shoulder-pads','wrap','team color'),('eye-black','face','no'),('football','held','no'),('cleats','feet','team color'),('wristband','wrap','team color'),('whistle','neck','no'),('kicking-tee','held','no')]),
 'hockey': (4, 2, [('helmet','head','team color'),('stick','held','no'),('puck','held','no'),('skates','feet','team color'),('gloves','held','team color'),('shoulder-pads','wrap','team color'),('tape-roll','held','no'),('beanie','head','team color')]),
 'pets': (4, 3, [('corgi','pet','no'),('golden-retriever','pet','no'),('dalmatian','pet','no'),('bunny','pet','no'),('hamster','pet','no'),('axolotl','pet','no'),('mini-dragon','pet','no'),('mini-robot','pet','no'),('dino','pet','no'),('frog','pet','no'),('turtle','pet','no'),('parrot','pet','no')]),
 'punk': (4, 3, [('liberty-spikes','hair','hair color'),('mohawk','hair','hair color'),('studded-vest','wrap','no (pin badges fixed)'),('plaid-tie-wrap','wrap','no'),('spike-wristband','wrap','no'),('combat-boots','feet','no (laces fixed)'),('studded-choker','neck','no'),('fishnet-sleeves','wrap','no'),('heart-shades','face','no'),('safety-pins','extra','no'),('skull-plush','pet','no'),('studded-cap','head','no')]),
 'grunge': (4, 3, [('slouch-beanie','head','primary'),('cardigan','wrap','primary'),('flannel-waist-wrap','wrap','no'),('distressed-high-tops','feet','no'),('round-shades','face','no'),('fingerless-gloves','wrap','primary'),('messy-long-hair','hair','hair color'),('beaded-choker','neck','no'),('cassette','held','no'),('acoustic-guitar','held','no'),('wool-scarf','neck','primary'),('torn-bucket-hat','head','primary')]),
 'careers': (4, 3, [('scientist-kit (goggles + lab coat + flask: split in code)','head+extra','coat = primary'),('stethoscope','neck','no'),('firefighter-helmet','head','no (plain shield)'),('police-cap','head','no (plain star)'),('hard-hat','head','primary'),('pilot-cap-aviators (cap + shades: split in code)','head+face','no'),('beret-palette (beret + palette: split in code)','head+held','beret = primary'),('chef-hat','head','no'),('astronaut-helmet','head','no'),('detective-cap-magnifier (cap + glass: split in code)','head+held','no'),('lab-coat','wrap','primary'),('safety-vest','wrap','no')]),
 'basketball-golf': (4, 3, [('basketball','held','no'),('headband-wristbands (3 pieces: split in code)','head+wrap','team color'),('high-tops','feet','team color'),('jersey','wrap','team color'),('mini-hoop','held','no'),('knee-socks','feet','team color'),('golf-visor','head','team color'),('golf-driver','held','no'),('golf-ball-tee','held','no'),('golf-shoes','feet','team color'),('golf-glove','wrap','team color'),('golf-flag','held','team color')]),
 'metal': (4, 3, [('wild-hair','hair','hair color'),('studded-jacket','wrap','no'),('flame-bandana','head','no'),('round-rocker-shades','face','no'),('flame-guitar','held','no'),('cuff-and-glove (2 pieces: split in code)','wrap','no'),('stage-boots','feet','no'),('pick-chain','neck','no'),('flame-amp','held','no'),('silver-notes','extra','no')]),
 'hiphop': (4, 3, [('snapback','head','primary'),('bucket-hat','head','primary'),('gold-chain-star','neck','no'),('headphones-neck','neck','primary'),('hoodie','wrap','primary'),('high-tops','feet','primary'),('boombox','held','no'),('gold-round-shades','face','no'),('splat-bandana','head','no'),('fingerless-gloves','wrap','primary')]),
 'kpop': (4, 3, [('bob-hair','hair','hair color (streak fixed pink)'),('star-earrings','face','no'),('sequin-jacket','wrap','no'),('platform-boots','feet','no'),('headset-mic','head','no'),('heart-lightstick','held','no'),('heart-choker','neck','no'),('round-clear-glasses','face','no'),('sequin-glove','wrap','no'),('star-fan-flag','held','no')]),
 'cottagecore': (4, 3, [('straw-sunhat','head','no'),('daisy-crown','head','no'),('cream-shawl','neck','primary'),('picnic-basket','held','no'),('mushroom-hat','head','no'),('lace-up-boots','feet','no'),('braid','hair','hair color'),('lantern-jar','held','no'),('snail-buddy','pet','no'),('wildflower-bunch','held','no')]),
 'western': (4, 3, [('cowboy-hat','head','primary'),('dotted-bandana','neck','no'),('cowboy-boots','feet','no'),('star-vest','wrap','no'),('lasso','held','no'),('buckle-belt','wrap','no'),('cactus-buddy','pet','no'),('hobby-horse','held','no'),('round-shades','face','no'),('tumbleweed-buddy','pet','no')]),
 'surfer': (4, 3, [('surfboard','held','no'),('shell-necklace','neck','no'),('board-shorts','wrap','primary (wave fixed blue)'),('rash-guard','wrap','primary'),('floppy-sunhat','head','primary'),('flip-flops','feet','primary'),('beach-hair','hair','hair color'),('mirror-shades','face','no'),('hermit-crab','pet','no'),('hibiscus-clip','head','no')]),
 'anime': (4, 3, [('spiky-hair','hair','hair color'),('long-ahoge-hair','hair','hair color'),('sailor-collar','wrap','no'),('round-glasses','face','no'),('gem-circlet','head','no'),('onigiri-plush','held','no'),('paper-fan','held','no'),('sweatdrop-sparkles','face','no'),('flowing-scarf','neck','primary'),('spirit-orb','pet','no')]),
 'preppy': (4, 3, [('pleated-skirt','wrap','primary'),('sweater-vest','wrap','primary'),('bow-tie','neck','no'),('ribbon-headband','head','no'),('loafers','feet','no'),('argyle-socks','feet','no'),('satchel','back','no'),('round-glasses','face','no'),('polo','wrap','primary'),('side-part-hair','hair','hair color')]),
 'hippie': (4, 3, [('flower-headband','head','no'),('rainbow-glasses','face','no'),('fringe-vest','wrap','no'),('tie-dye-bandana','head','no'),('bead-necklace','neck','no'),('bell-bottoms','wrap','no'),('flower-hair','hair','hair color'),('flower-guitar','held','no'),('tassel-bag','back','no'),('flower-sandals','feet','no')]),
 'steampunk': (4, 3, [('goggle-top-hat','head','no'),('brass-goggles','face','no'),('gear-shoulders','wrap','no'),('corset-vest','wrap','no'),('key-necklace','neck','no'),('brass-boots','feet','no'),('brass-robot','pet','no'),('pocket-watch','neck','no'),('brass-wings','back','no'),('steam-backpack','back','no')]),
 'cyber': (4, 3, [('visor','face','no'),('glow-hood-cloak','wrap','no'),('neck-ring','neck','no'),('neon-boots','feet','no'),('led-headphones','head','no'),('circuit-armband','wrap','no'),('hover-drone','pet','no'),('utility-bag','back','no'),('fiber-optic-hair','hair','hair color (tips fixed glow)'),('neon-cat-ears','head','no')]),
 'raver': (4, 3, [('neon-star-shades','face','no'),('fluffy-legwarmers','feet','primary'),('bead-bracelets','wrap','no'),('glowstick-crown','head','no'),('holo-bucket-hat','head','no'),('neon-platforms','feet','no'),('led-jacket','wrap','no'),('pompom-backpack','back','primary'),('fluffy-cat-headphones','head','primary'),('glitter-orb-buddy','pet','no')]),
 'athleisure': (4, 3, [('track-jacket','wrap','primary'),('joggers','wrap','primary'),('ponytail','hair','hair color (scrunchie primary)'),('running-visor','head','primary'),('running-shoes','feet','primary'),('water-bottle','held','primary'),('yoga-mat','back','primary'),('earbuds','face','no'),('fitness-band','wrap','primary'),('gym-duffel','back','primary')]),
}
