#!/usr/bin/env python3
"""Mascot-maker item packs (FRIDAY-QUEUE 5b / 51): pack -> grid + [(piece id, slot, colorable parts)].
Slots follow INTEGRATION.md layers: head (hat/hair on top), hair, face (decals + glasses), neck (drape/necklace/scarf), wrap (worn on the
body: straps, belts, cloaks front), back (behind the body), held (in the hand), feet, pet (buddy beside the feet), extra.
Colorable = neutral white/grey clay that the code tints (hair/clothing/team color); 'no' = fixed colors."""
PACKS = {
 'goth': (4, 3, [('lace-choker','neck','no'),('velvet-cape','wrap+back','no (purple lining)'),('bat-wing-clip','head','no'),('long-side-hair','hair','hair color'),('winged-liner-lips','face','no'),('skull-bow','head','no'),('platform-boots','feet','no'),('lace-umbrella','held','no'),('moon-pendant','neck','no'),('bat-sunglasses','face','no'),('black-cat-plush','pet','no'),('purple-lantern','held','no')]),
 'skater': (4, 3, [('skateboard','held','no (wheels, deck)'),('skate-helmet','head','body = team/primary color'),('flat-brim-cap','head','primary'),('bucket-hat','head','primary'),('skate-shoes','feet','primary'),('zip-hoodie','wrap','primary'),('wrist-guards','wrap','primary'),('sweatband','head','primary'),('wayfarer-shades','face','no'),('headphones','head','primary'),('star-stickers','extra','no'),('messenger-bag','back','primary')]),
 'kawaii': (4, 3, [('bunny-ear-band','head','primary'),('cat-ear-band','head','primary'),('giant-bow','head','primary'),('twin-tails','hair','hair color'),('star-glasses','face','no'),('blush-stickers','face','no'),('rainbow-scarf','neck','no'),('platform-sneakers','feet','primary'),('heart-backpack','back','primary'),('star-wand','held','no'),('teddy-buddy','pet','no'),('strawberry-hat','head','primary (leaf fixed)')]),
 'music': (4, 3, [('drumsticks','held','no'),('keytar','held','no'),('violin-bow','held','no'),('trumpet','held','no'),('dj-headphones','head','no'),('boombox','held','no'),('note-aura','extra','no'),('rockstar-shades','face','no'),('glitter-mic','held','no'),('baton','held','no'),('tambourine','held','no'),('mini-drum','held','no')]),
 'gaming': (4, 2, [('controller','held','no'),('headset','head','no'),('pixel-shades','face','no'),('handheld','held','no'),('vr-goggles','face','no'),('arcade-token','extra','no'),('joystick','held','no'),('pixel-heart','pet','no')]),
 'baseball': (4, 2, [('cap','head','team color'),('batting-helmet','head','team color'),('glove','held','no'),('bat','held','no'),('ball','held','no'),('cleats','feet','team color'),('eye-black','face','no'),('wristband','wrap','team color')]),
 'soccer': (4, 2, [('ball','held','no'),('cleats','feet','team color'),('shin-guards','feet','team color'),('headband','head','team color'),('captain-armband','wrap','team color'),('goalie-gloves','held','team color'),('whistle','neck','no'),('corner-flag','held','team color')]),
 'emo': (4, 3, [('fringe-hair','hair','hair color'),('studded-belt','wrap','no'),('striped-arm-warmers','wrap','no'),('checker-wristbands','wrap','no'),('skinny-tie','neck','no'),('star-shades','face','no'),('hair-clips','head','no'),('hoodie','wrap','primary'),('checker-high-tops','feet','no'),('pink-headphones','head','no'),('heart-plasters','face','no'),('heart-balloon','held','no')]),
 'football': (4, 2, [('helmet','head','team color'),('shoulder-pads','wrap','team color'),('eye-black','face','no'),('football','held','no'),('cleats','feet','team color'),('wristband','wrap','team color'),('whistle','neck','no'),('kicking-tee','held','no')]),
 'hockey': (4, 2, [('helmet','head','team color'),('stick','held','no'),('puck','held','no'),('skates','feet','team color'),('gloves','held','team color'),('shoulder-pads','wrap','team color'),('tape-roll','held','no'),('beanie','head','team color')]),
}
