// GENERATED by packages/core/scripts/gen-mode-catalog.mjs from modes.json — DO NOT EDIT.
// Run `pnpm gen:modes` to regenerate. Edit packages/core/modes.json instead.

export type ModeGroup = 'core' | 'more';
export type ModeEngine = 'word' | 'custom';
export type GuessSemantics = 'guesses' | 'mistakes' | 'checks' | 'overPar' | 'misses' | 'rank';

export interface ModeMeta {
  id: string;
  dbKey: string | null;
  title: string;
  shortTitle: string;
  shareLabel: string;
  desc: string;
  accentHex: string;
  glyph: string | null;
  romanNumeral: string | null;
  dailyEligible: boolean;
  /** Home grid tile (core) or More Games sheet (more). */
  group: ModeGroup;
  /** Counts toward the Daily Sweep / Flawless. */
  sweep: boolean;
  /** Shared word reducer, or the mode's own view. */
  engine: ModeEngine;
  /** What guess_count means, for labels. */
  guessSemantics: GuessSemantics;
  /** The perfect guess_count; display shows guess_count − guessBase. */
  guessBase: number;
  /** Reading order of the home grid (2 × 5); the array order stays the sweep/canonical order. */
  homeSlot: number;
  /** Rendered as a full-width tile UNDER the grid (More Games band, VS Battle live tile), not a grid cell. */
  homeWide: boolean;
  /** Compiled in and visible (a remote flag may still hide it). */
  enabled: boolean;
  flagKey: string | null;
  /** More Games sheet section key. */
  category: string | null;
  guideSlug: string | null;
}

export interface SweepEra { since: string; modes: string[] }
export interface MoreCategory { key: string; title: string }

export const MODES: ModeMeta[] = [
  {
    "id": "practice",
    "dbKey": "DUEL",
    "title": "Classic",
    "shortTitle": "Classic",
    "shareLabel": "Classic",
    "desc": "1 word, 6 tries",
    "accentHex": "#7c3aed",
    "glyph": "C",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "classic",
    "homeSlot": 0,
    "homeWide": false
  },
  {
    "id": "vs",
    "dbKey": null,
    "title": "VS Battle",
    "shortTitle": "VS",
    "shareLabel": "VS Battle",
    "desc": "Real-time PvP",
    "accentHex": "#0d9488",
    "glyph": null,
    "romanNumeral": null,
    "dailyEligible": false,
    "group": "core",
    "sweep": false,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": null,
    "homeSlot": 8,
    "homeWide": true
  },
  {
    "id": "quordle",
    "dbKey": "QUORDLE",
    "title": "QuadWord",
    "shortTitle": "Quad",
    "shareLabel": "QuadWord",
    "desc": "4 words at once",
    "accentHex": "#ec4899",
    "glyph": "IV",
    "romanNumeral": "IV",
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 4,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "quadword",
    "homeSlot": 2,
    "homeWide": false
  },
  {
    "id": "octordle",
    "dbKey": "OCTORDLE",
    "title": "OctoWord",
    "shortTitle": "Octo",
    "shareLabel": "OctoWord",
    "desc": "8 boards, 13 tries",
    "accentHex": "#7e22ce",
    "glyph": "VIII",
    "romanNumeral": "VIII",
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 8,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "octoword",
    "homeSlot": 3,
    "homeWide": false
  },
  {
    "id": "sequence",
    "dbKey": "SEQUENCE",
    "title": "Succession",
    "shortTitle": "Succ.",
    "shareLabel": "Succession",
    "desc": "4 words, one by one",
    "accentHex": "#2563eb",
    "glyph": "S",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 4,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "succession",
    "homeSlot": 4,
    "homeWide": false
  },
  {
    "id": "rescue",
    "dbKey": "RESCUE",
    "title": "Deliverance",
    "shortTitle": "Deliv.",
    "shareLabel": "Deliverance",
    "desc": "4 prefilled boards",
    "accentHex": "#059669",
    "glyph": "D",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 4,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "deliverance",
    "homeSlot": 5,
    "homeWide": false
  },
  {
    "id": "six",
    "dbKey": "DUEL_6",
    "title": "Six",
    "shortTitle": "Six",
    "shareLabel": "Classic Six",
    "desc": "6 letters, 7 tries",
    "accentHex": "#06b6d4",
    "glyph": "6",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "six",
    "homeSlot": 6,
    "homeWide": false
  },
  {
    "id": "seven",
    "dbKey": "DUEL_7",
    "title": "Seven",
    "shortTitle": "Seven",
    "shareLabel": "Classic Seven",
    "desc": "7 letters, 8 tries",
    "accentHex": "#84cc16",
    "glyph": "7",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "seven",
    "homeSlot": 7,
    "homeWide": false
  },
  {
    "id": "gauntlet",
    "dbKey": "GAUNTLET",
    "title": "Gauntlet",
    "shortTitle": "Gauntlet",
    "shareLabel": "Gauntlet",
    "desc": "5 escalating stages",
    "accentHex": "#d97706",
    "glyph": "G",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "core",
    "sweep": true,
    "engine": "word",
    "guessSemantics": "guesses",
    "guessBase": 21,
    "enabled": true,
    "flagKey": null,
    "category": null,
    "guideSlug": "gauntlet",
    "homeSlot": 1,
    "homeWide": false
  },
  {
    "id": "propernoundle",
    "dbKey": "PROPERNOUNDLE",
    "title": "ProperNoundle",
    "shortTitle": "Proper",
    "shareLabel": "ProperNoundle",
    "desc": "Guess famous names",
    "accentHex": "#dc2626",
    "glyph": "P",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": null,
    "category": "trivia",
    "guideSlug": "propernoundle",
    "homeSlot": 109,
    "homeWide": false
  },
  {
    "id": "more",
    "dbKey": null,
    "title": "More Games",
    "shortTitle": "More",
    "shareLabel": "More Games",
    "desc": "Sudocious, Muddle and more",
    "accentHex": "#4f46e5",
    "glyph": "+",
    "romanNumeral": null,
    "dailyEligible": false,
    "group": "core",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "guesses",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "menu.more",
    "category": null,
    "guideSlug": null,
    "homeSlot": 9,
    "homeWide": true
  },
  {
    "id": "sudoku",
    "dbKey": "SUDOKU",
    "title": "Sudocious",
    "shortTitle": "Sudocious",
    "shareLabel": "Sudocious",
    "desc": "Daily number logic",
    "accentHex": "#1e40af",
    "glyph": "9",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "mistakes",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.sudoku",
    "category": "logic",
    "guideSlug": "sudocious",
    "homeSlot": 111,
    "homeWide": false
  },
  {
    "id": "scramble",
    "dbKey": "SCRAMBLE",
    "title": "Muddle",
    "shortTitle": "Muddle",
    "shareLabel": "Muddle",
    "desc": "Unscramble the punchline",
    "accentHex": "#f97316",
    "glyph": "M",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "checks",
    "guessBase": 5,
    "enabled": true,
    "flagKey": "mode.scramble",
    "category": "word",
    "guideSlug": "muddle",
    "homeSlot": 112,
    "homeWide": false
  },
  {
    "id": "hub",
    "dbKey": "HUB",
    "title": "Hubbub",
    "shortTitle": "Hubbub",
    "shareLabel": "Hubbub",
    "desc": "Seven letters, one hub",
    "accentHex": "#c026d3",
    "glyph": "H",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "rank",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.hub",
    "category": "word",
    "guideSlug": "hubbub",
    "homeSlot": 113,
    "homeWide": false
  },
  {
    "id": "crossword",
    "dbKey": "CROSSWORD",
    "title": "Crosswordocious",
    "shortTitle": "Crossword",
    "shareLabel": "Crosswordocious",
    "desc": "Fill-in sayings crossword",
    "accentHex": "#475569",
    "glyph": "X",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "checks",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.crossword",
    "category": "trivia",
    "guideSlug": "crosswordocious",
    "homeSlot": 114,
    "homeWide": false
  },
  {
    "id": "groups",
    "dbKey": "GROUPS",
    "title": "Kindred",
    "shortTitle": "Kindred",
    "shareLabel": "Kindred",
    "desc": "Four groups of four",
    "accentHex": "#9f1239",
    "glyph": "K",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "guesses",
    "guessBase": 4,
    "enabled": true,
    "flagKey": "mode.groups",
    "category": "logic",
    "guideSlug": "kindred",
    "homeSlot": 115,
    "homeWide": false
  },
  {
    "id": "ladder",
    "dbKey": "LADDER",
    "title": "Letter Ladder",
    "shortTitle": "Ladder",
    "shareLabel": "Letter Ladder",
    "desc": "One letter at a time",
    "accentHex": "#0284c7",
    "glyph": "L",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "overPar",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.ladder",
    "category": "word",
    "guideSlug": "letter-ladder",
    "homeSlot": 116,
    "homeWide": false
  },
  {
    "id": "cryptogram",
    "dbKey": "CRYPTOGRAM",
    "title": "Codebreaker",
    "shortTitle": "Code",
    "shareLabel": "Codebreaker",
    "desc": "Crack the coded saying",
    "accentHex": "#92400e",
    "glyph": "?",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "checks",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.cryptogram",
    "category": "logic",
    "guideSlug": "codebreaker",
    "homeSlot": 117,
    "homeWide": false
  },
  {
    "id": "wordsearch",
    "dbKey": "WORDSEARCH",
    "title": "Spyglass",
    "shortTitle": "Spyglass",
    "shareLabel": "Spyglass",
    "desc": "Themed word search",
    "accentHex": "#4d7c0f",
    "glyph": "W",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "misses",
    "guessBase": 10,
    "enabled": true,
    "flagKey": "mode.wordsearch",
    "category": "word",
    "guideSlug": "spyglass",
    "homeSlot": 118,
    "homeWide": false
  },
  {
    "id": "regions",
    "dbKey": "REGIONS",
    "title": "Starsweep",
    "shortTitle": "Stars",
    "shareLabel": "Starsweep",
    "desc": "One star per color region",
    "accentHex": "#ca8a04",
    "glyph": "*",
    "romanNumeral": null,
    "dailyEligible": true,
    "group": "more",
    "sweep": false,
    "engine": "custom",
    "guessSemantics": "mistakes",
    "guessBase": 1,
    "enabled": true,
    "flagKey": "mode.regions",
    "category": "logic",
    "guideSlug": "starsweep",
    "homeSlot": 119,
    "homeWide": false
  }
];

export const MODE_BY_ID: Record<string, ModeMeta> = Object.fromEntries(MODES.map((m) => [m.id, m]));
export const MODE_BY_DBKEY: Record<string, ModeMeta> = Object.fromEntries(
  MODES.filter((m) => m.dbKey).map((m) => [m.dbKey as string, m]),
);
/** Enabled modes only — what this build shows anywhere. */
export const ENABLED_MODES: ModeMeta[] = MODES.filter((m) => m.enabled);
/** Daily modes (VS excluded), canonical order — every daily-recordable mode this build knows. */
export const DAILY_MODES: ModeMeta[] = ENABLED_MODES.filter((m) => m.dailyEligible && m.dbKey);
/** The current required Daily Sweep set, canonical order. */
export const SWEEP_MODES: ModeMeta[] = DAILY_MODES.filter((m) => m.sweep);
/** Home grid tiles. */
export const CORE_MODES: ModeMeta[] = ENABLED_MODES.filter((m) => m.group === 'core').sort((a, b) => a.homeSlot - b.homeSlot);
/** More Games sheet entries. */
export const MORE_GAME_MODES: ModeMeta[] = ENABLED_MODES.filter((m) => m.group === 'more');
export const MORE_CATEGORIES: MoreCategory[] = [{"key":"word","title":"Word"},{"key":"trivia","title":"Trivia"},{"key":"logic","title":"Logic"}];

/** Sweep eras, newest first: which dbKeys formed the required sweep on a given local day. Append-only. */
export const SWEEP_ERAS: SweepEra[] = [{"since":"2026-09-25","modes":["DUEL","QUORDLE","OCTORDLE","SEQUENCE","RESCUE","GAUNTLET","DUEL_6","DUEL_7"]},{"since":"2026-05-21","modes":["DUEL","QUORDLE","OCTORDLE","SEQUENCE","RESCUE","GAUNTLET","PROPERNOUNDLE","DUEL_6","DUEL_7"]},{"since":"0000-00-00","modes":["DUEL","QUORDLE","OCTORDLE","SEQUENCE","RESCUE","GAUNTLET","PROPERNOUNDLE"]}];

/** The dbKeys a player had to record on `day` (local YYYY-MM-DD) for a sweep. ISO string compare is safe. */
export function sweepModesFor(day: string): string[] {
  for (const era of SWEEP_ERAS) if (day >= era.since) return era.modes;
  return SWEEP_ERAS[SWEEP_ERAS.length - 1].modes;
}
export function requiredSweepCount(day: string): number { return sweepModesFor(day).length; }
