package com.wordocious.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-platform parity guard for FINISH_SPEC AN3: swatches, backdrops, the seeded
 * default, nearest-swatch, validation, Pro enforcement and the cast presets must match
 * packages/core/src/avatar-config.ts (avatar-config-fixtures.json, generated by
 * packages/core/scripts/gen-parity-fixtures.ts). Each fixture config is compared key by
 * key, so fields the fixture doesn't carry (yet) don't fail the parity check.
 */
class AvatarConfigFixtureTest {
    private val root: JsonObject by lazy {
        Json.parseToJsonElement(javaClass.classLoader!!.getResource("fixtures/avatar-config-fixtures.json")!!.readText()).jsonObject
    }

    private fun str(e: JsonElement?): String? = (e as? JsonPrimitive)?.takeUnless { it is JsonNull }?.contentOrNull

    private fun assertConfig(label: String, expected: JsonObject, actual: AvatarConfig) {
        val got = avatarToJson(actual)
        for ((k, v) in expected) assertEquals("$label.$k", v, got[k])
    }

    private fun config(o: JsonObject): AvatarConfig = validateAvatar(o, AvatarConfig())

    @Test
    fun swatches_and_backdrops_match() {
        val colors = root["colors"]!!.jsonArray.map { it.jsonObject }
        assertEquals(colors.map { str(it["id"]) }, AvatarOptions.SWATCHES.map { it.id })
        assertEquals(colors.map { str(it["hex"]) }, AvatarOptions.SWATCHES.map { it.hex })
        root["backdrops"]?.jsonArray?.map { it.jsonObject }?.let { bds ->
            assertEquals(bds.map { str(it["id"]) }, AvatarOptions.BACKDROPS.map { it.id })
            assertEquals(bds.map { str(it["kind"]) }, AvatarOptions.BACKDROPS.map { it.kind })
            assertEquals(bds.map { b -> b["colors"]!!.jsonArray.map { str(it) } }, AvatarOptions.BACKDROPS.map { it.colors })
        }
    }

    @Test
    fun defaults_match() {
        val rows = root["defaults"]!!.jsonArray
        assertTrue(rows.size >= 30)
        for (r in rows.map { it.jsonObject }) {
            val user = (str(r["seed"]) ?: str(r["userId"])) ?: ""
            val accent = str(r["accent"])
            assertConfig("default($user,$accent)", r["config"]!!.jsonObject, defaultAvatar(user, accent))
        }
    }

    @Test
    fun nearest_matches() {
        for (r in root["nearest"]!!.jsonArray.map { it.jsonObject }) {
            assertEquals(str(r["hex"]), str(r["id"]), nearestAvatarColor(str(r["hex"])))
        }
    }

    @Test
    fun validate_matches() {
        val fb = config(root["fallback"]!!.jsonObject)
        assertConfig("fallback", root["fallback"]!!.jsonObject, defaultAvatar("fixture", "#2563eb"))
        for ((i, r) in root["validate"]!!.jsonArray.map { it.jsonObject }.withIndex()) {
            val raw = r["raw"]
            assertConfig("validate[$i]", r["result"]!!.jsonObject, validateAvatar(if (raw is JsonNull) null else raw, fb))
        }
    }

    @Test
    fun pro_and_presets_match() {
        val fb = config(root["fallback"]!!.jsonObject)
        val c = fb.copy(head = "crown", frame = "diamond", neck = "wings", bg = "aurora")
        for (r in root["pro"]!!.jsonArray.map { it.jsonObject }) {
            val isPro = r["isPro"]!!.jsonPrimitive.booleanOrNull!!
            assertConfig("pro($isPro)", r["result"]!!.jsonObject, enforceAvatarPro(c, isPro))
        }
        for (r in root["presets"]!!.jsonArray.map { it.jsonObject }) {
            val id = str(r["castId"])!!
            assertConfig("preset($id)", r["config"]!!.jsonObject, castPreset(id))
            assertEquals(castPreset(id), AvatarPresets.forCast(id))
        }
    }

    @Test
    fun with_photo_and_display_fixtures_match() {
        val withPhoto = root["withPhoto"]?.jsonArray ?: return
        for (r in withPhoto.map { it.jsonObject }) {
            val user = (str(r["seed"]) ?: str(r["userId"])) ?: ""
            assertConfig("withPhoto($user)", r["config"]!!.jsonObject, defaultAvatar(user, str(r["accent"]), hasPhoto = true))
        }
        for ((i, r) in root["display"]!!.jsonArray.map { it.jsonObject }.withIndex()) {
            val hasPhoto = r["hasPhoto"]!!.jsonPrimitive.booleanOrNull!!
            val fb = defaultAvatar("fixture", "#2563eb", hasPhoto)
            assertEquals("display[$i]", str(r["result"]), validateAvatar(r["raw"], fb).display)
        }
    }

    @Test
    fun display_defaults_by_photo_and_validates() {
        assertEquals("mascot", defaultAvatar("x").display)
        assertEquals("photo", defaultAvatar("x", hasPhoto = true).display)
        val fb = defaultAvatar("x", hasPhoto = true)
        assertEquals("mascot", validateAvatar(Json.parseToJsonElement("""{"display":"mascot"}"""), fb).display)
        assertEquals("photo", validateAvatar(Json.parseToJsonElement("""{"display":"hologram"}"""), fb).display)
    }

    @Test
    fun stored_detection_and_json_round_trip() {
        assertFalse(isStoredAvatar(null))
        assertFalse(isStoredAvatar(JsonNull))
        assertFalse(isStoredAvatar(JsonArray(emptyList())))
        val c = AvatarConfig(body = "star", color = "mint", pattern = "dots", patternColor = "pink", head = "tiara", bg = "galaxy", display = "photo")
        assertTrue(isStoredAvatar(avatarToJson(c)))
        assertEquals(c, validateAvatar(avatarToJson(c)))
        // Unknown string ids and non-string values fall back field by field.
        val v = validateAvatar(Json.parseToJsonElement("""{"body":7,"head":"fedora","bg":"lava","color":"PURPLE"}"""), c)
        assertEquals("star", v.body); assertEquals("tiara", v.head); assertEquals("galaxy", v.bg); assertEquals("mint", v.color)
    }
}
