package com.wordocious.core

import com.google.gson.Gson
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-platform parity guard for the bot cast (FINISH_SPEC D1–D2): the cast table,
 * the legacy id map, the legacy ladder migration and the Bot of the Day rotation must
 * match packages/core/src/bot-cast.ts exactly (vs-lobby-fixtures.json, generated by
 * packages/core/scripts/gen-parity-fixtures.ts).
 */
class BotCastFixtureTest {
    private data class Cast(
        val id: String, val name: String, val castId: String, val rung: Int, val tier: String,
        val guesses: List<Int>?, val trait: String, val color: String, val solveLine: String,
    )
    private data class Legacy(val id: String, val canonical: String)
    private data class LegacyCleared(val old: Int, val cleared: Int)
    private data class BotOfDay(val day: String, val id: String)
    private data class Fixtures(val cast: List<Cast>, val legacy: List<Legacy>, val legacyCleared: List<LegacyCleared>, val botOfDay: List<BotOfDay>)

    private val f: Fixtures by lazy {
        Gson().fromJson(javaClass.classLoader!!.getResource("fixtures/vs-lobby-fixtures.json")!!.readText(), Fixtures::class.java)
    }

    @Test
    fun cast_matches_shared_fixtures() {
        assertEquals(f.cast.map { it.id }, BotCast.IDS)
        for (c in f.cast) {
            val m = BotCast.member(c.id)
            assertNotNull(c.id, m)
            m!!
            assertEquals(c.name, m.name)
            assertEquals(c.castId, m.castId)
            assertEquals(c.rung, m.rung)
            assertEquals(c.tier, m.tier.raw)
            assertEquals(c.guesses, m.guesses?.let { listOf(it.first, it.last) })
            assertEquals(c.trait, m.trait)
            assertEquals(c.color.lowercase(), "#%06x".format(m.color and 0xFFFFFF))
            assertEquals(c.solveLine, BotCast.solveLine(m))
        }
    }

    @Test
    fun legacy_ids_and_ladder_match_shared_fixtures() {
        assertTrue(f.legacy.isNotEmpty())
        for (l in f.legacy) assertEquals(l.id, l.canonical, BotCast.canonicalId(l.id))
        for (l in f.legacyCleared) assertEquals("old ${l.old}", l.cleared, BotCast.migrateLegacyLadderCleared(l.old))
    }

    @Test
    fun bot_of_the_day_matches_shared_fixtures() {
        assertTrue(f.botOfDay.isNotEmpty())
        for (b in f.botOfDay) assertEquals(b.day, b.id, BotCast.botOfTheDay(b.day).id)
    }
}
