package com.wordocious.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.longOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-platform parity guard for the Friends overhaul (2026-10-01): the pocket
 * game rules, the card lines and headlines, presence, friend streaks and the
 * Friends banner words must match packages/core/src/friendly-games.ts exactly
 * (friendly-games-fixtures.json, generated by gen-parity-fixtures.ts — the
 * scripts there: coin flips 0.1, 0.1, 0.1, 0.7, 0.3; Pass answer RISKS; card
 * lines with minutesAgo 4 for side a vs "Doug" and 75 for side b vs "BT").
 */
class FriendlyGamesFixtureTest {
    private val root: JsonObject by lazy {
        Json.parseToJsonElement(javaClass.classLoader!!.getResource("fixtures/friendly-games-fixtures.json")!!.readText()).jsonObject
    }

    private fun JsonElement?.strOrNull(): String? = (this as? JsonPrimitive)?.takeIf { this !is JsonNull }?.contentOrNull

    @Test
    fun games_replay_every_step() {
        val games = root["games"]!!.jsonArray
        assertEquals(4, games.size)
        var steps = 0
        for (g in games) {
            val kind = FriendlyKind.from(g.jsonObject["kind"].strOrNull())!!
            val solution = if (kind == FriendlyKind.PASS) "RISKS" else null
            val flips = ArrayDeque(if (kind == FriendlyKind.COIN) listOf(0.1, 0.1, 0.1, 0.7, 0.3) else emptyList())
            val ctx = MoveContext(random = { flips.removeFirstOrNull() ?: 0.1 }, solution = solution)
            var s = newFriendlyState(kind)
            for (stepEl in g.jsonObject["steps"]!!.jsonArray) {
                val step = stepEl.jsonObject
                val by = Side.from(step["by"].strOrNull())!!
                val move = FriendlyMove.fromJson(step["move"])!!
                // The move's wire shape round-trips (what the app POSTs).
                assertEquals("move json $step", step["move"], move.toJson())
                val r = applyFriendlyMove(s, by, move, ctx)
                assertEquals("ok $step", step["ok"]!!.jsonPrimitive.boolean, r is MoveResult.Ok)
                if (r is MoveResult.Ok) s = r.state
                val expected = decodeFriendlyState(step["state"])
                assertEquals("state $step", expected, s)
                assertEquals("turn $step", step["turn"].strOrNull(), whoseTurn(s)?.raw)
                assertEquals("winner $step", step["winner"].strOrNull(), friendlyWinner(s)?.raw)
                assertEquals("headlineA $step", step["headlineA"].strOrNull(), friendlyHeadline(s, Side.A))
                assertEquals("headlineB $step", step["headlineB"].strOrNull(), friendlyHeadline(s, Side.B))
                assertEquals("cardA $step", step["cardA"].strOrNull(), friendlyCardLine(s, Side.A, "Doug", 4))
                assertEquals("cardB $step", step["cardB"].strOrNull(), friendlyCardLine(s, Side.B, "BT", 75))
                steps++
            }
        }
        assertEquals(26, steps)
    }

    @Test
    fun boards_find_the_line() {
        val boards = root["boards"]!!.jsonArray
        assertTrue(boards.isNotEmpty())
        for (c in boards) {
            val o = c.jsonObject
            val board = o["board"]!!.jsonArray.map { Side.from(it.strOrNull()) }
            val got = tttLine(board)
            val line = o["line"]
            if (line == null || line is JsonNull) {
                assertNull("line $o", got)
            } else {
                assertNotNull("line $o", got)
                assertEquals("side $o", line.jsonObject["side"].strOrNull(), got!!.side.raw)
                assertEquals("cells $o", line.jsonObject["cells"]!!.jsonArray.map { it.jsonPrimitive.int }, got.cells)
            }
        }
    }

    @Test
    fun presence_matches() {
        val cases = root["presence"]!!.jsonArray
        assertEquals(9, cases.size)
        for (c in cases) {
            val o = c.jsonObject
            val last = (o["lastSeenMs"] as? JsonPrimitive)?.longOrNull
            val now = o["nowMs"]!!.jsonPrimitive.long
            val activity = o["activity"].strOrNull()
            assertEquals("online $o", o["online"]!!.jsonPrimitive.boolean, isOnline(last, now))
            assertEquals("line $o", o["line"].strOrNull(), presenceLine(last, activity, now))
        }
    }

    @Test
    fun friend_streaks_match() {
        val cases = root["streaks"]!!.jsonArray
        assertEquals(5, cases.size)
        for (c in cases) {
            val o = c.jsonObject
            val mine = o["mine"]!!.jsonArray.map { it.jsonPrimitive.content }
            val theirs = o["theirs"]!!.jsonArray.map { it.jsonPrimitive.content }
            assertEquals("streak $o", o["streak"]!!.jsonPrimitive.int, friendStreak(mine, theirs, o["today"]!!.jsonPrimitive.content))
        }
    }

    @Test
    fun banner_words_match() {
        val cases = root["banners"]!!.jsonArray
        assertEquals(9, cases.size)
        for (c in cases) {
            val o = c.jsonObject
            val i = o["input"]!!.jsonObject
            val input = FriendsBannerInput(
                friendCount = i["friendCount"]!!.jsonPrimitive.int,
                online = (i["online"] as JsonArray).map { it.jsonPrimitive.content },
                myRank = i["myRank"]!!.jsonPrimitive.int,
                myPoints = i["myPoints"]!!.jsonPrimitive.int,
                leaderName = i["leaderName"]!!.jsonPrimitive.content,
                leaderPoints = i["leaderPoints"]!!.jsonPrimitive.int,
                nextPoints = i["nextPoints"]!!.jsonPrimitive.int,
            )
            assertEquals("headline $o", o["headline"].strOrNull(), friendsBannerHeadline(input))
            assertEquals("clock $o", o["clock"].strOrNull(), friendsBannerClockLine(input, "04:12:08"))
        }
    }

    @Test
    fun hidden_picks_and_constants() {
        // The server sends the friend's open RPS pick as "hidden".
        val view = decodeFriendlyState(Json.parseToJsonElement("""{"kind":"rps","picks":{"a":"hidden"},"rounds":[],"score":{"a":0,"b":0}}"""))
        assertTrue(view is RpsState)
        assertEquals(RpsPick.HIDDEN, (view as RpsState).picks[Side.A])
        assertEquals(FriendlyTurn.B, whoseTurn(view))
        val s = (applyFriendlyMove(newFriendlyState(FriendlyKind.RPS), Side.A, FriendlyMove.Rps(RpsPick.PAPER)) as MoveResult.Ok).state
        assertEquals(RpsPick.HIDDEN, (friendlyStateFor(s, Side.B) as RpsState).picks[Side.A])
        assertEquals(RpsPick.PAPER, (friendlyStateFor(s, Side.A) as RpsState).picks[Side.A])
        assertTrue(applyFriendlyMove(s, Side.A, FriendlyMove.Rps(RpsPick.ROCK)) is MoveResult.Err)
        assertEquals(listOf("Bragging rights", "Loser picks tonight's VS mode", "Winner goes first next time"), COIN_STAKES)
        assertEquals("Bragging rights", (newFriendlyState(FriendlyKind.COIN, "anything") as CoinState).stake)
        assertEquals("Tic-Tac-Tile", FriendlyKind.TTT.title)
        assertEquals("Pass the Puzzle", FRIENDLY_TITLES[FriendlyKind.PASS])
        // Pass the Puzzle rejects a non-word and an invalid word with the TS errors.
        val pass = newFriendlyState(FriendlyKind.PASS)
        assertEquals(MoveResult.Err("Five letters, please"), applyFriendlyMove(pass, Side.A, FriendlyMove.Pass("abc"), MoveContext(solution = "RISKS")))
        assertEquals(MoveResult.Err("Not in the word list"), applyFriendlyMove(pass, Side.A, FriendlyMove.Pass("ZZZZZ"), MoveContext(solution = "RISKS", isValidWord = { it != "ZZZZZ" })))
    }
}
