# Ship the dress-up art (ChatGPT, keyed by make.py) to the three apps as art-dress-<id>:
#   web      apps/web/public/art/<name>.webp (+ apps/web/lib/dress-art.ts sizes, spread into ART_SIZE)
#   Android  res/drawable-nodpi/<name with _>.webp (kept through shrinking by res/raw/keep_dress.xml)
#   iOS      Assets.xcassets/<name>.imageset/<name>.png
#   python3 docs/design/profile-2026-10-05/art/ship.py
# The alternatives stay here (podiums-*.png, ribbons-*.png, …) so the founder can swap: change PICK below.
import json, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
WEB = os.path.join(REPO, 'apps', 'web', 'public', 'art')
IOS = os.path.join(REPO, 'apps', 'ios', 'Wordocious', 'Resources', 'Assets.xcassets')
DROID = os.path.join(REPO, 'apps', 'android', 'app', 'src', 'main', 'res', 'drawable-nodpi')

PICK = {'podium': 'podiums-3', 'ribbon': 'ribbons-1'}
RIBBON_CAPS = {'ribbons-1': (272, 1343), 'ribbons-2': (232, 1384), 'ribbons-3': (90, 1525)}
SIZES = {}


def fit(im, w=None, h=None):
    if w and im.width > w:
        im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
    if h and im.height != h:
        im = im.resize((max(1, round(im.width * h / im.height)), h), Image.LANCZOS)
    return im


def ship(name, im):
    im.save(os.path.join(WEB, f'{name}.webp'), 'WEBP', quality=92, method=6)
    im.save(os.path.join(DROID, name.replace('-', '_') + '.webp'), 'WEBP', quality=92, method=6)
    iset = os.path.join(IOS, f'{name}.imageset')
    os.makedirs(iset, exist_ok=True)
    im.save(os.path.join(iset, f'{name}.png'), optimize=True)
    with open(os.path.join(iset, 'Contents.json'), 'w') as f:
        json.dump({'images': [{'filename': f'{name}.png', 'idiom': 'universal'}], 'info': {'author': 'xcode', 'version': 1}}, f, indent=2)
    SIZES[name] = im.size


def load(n):
    p = os.path.join(HERE, n + '.png')
    return Image.open(p).convert('RGBA') if os.path.exists(p) else None


# The stage podium the mascot stands on (shown ~260 pt wide).
ship('art-dress-podium', fit(load(PICK['podium']), w=780))
# The title ribbon, three slices (left cap · 8-px middle that stretches · right cap), 120 px tall.
r = load(PICK['ribbon']); L, R = RIBBON_CAPS[PICK['ribbon']]; m = r.width // 2
ship('art-dress-ribbon-l', fit(r.crop((0, 0, L + 6, r.height)), h=120))
ship('art-dress-ribbon-m', fit(r.crop((m - 4, 0, m + 4, r.height)), h=120))
ship('art-dress-ribbon-r', fit(r.crop((R - 6, 0, r.width, r.height)), h=120))
# Everything else: (piece file, name, max width)
EXTRA = [('room-2', 'art-dress-bulbs', 900), ('room-1', 'art-dress-curtain-l', 240), ('room-3', 'art-dress-curtain-r', 240),
         ('room-4', 'art-dress-tag-new', 160), ('room-5', 'art-dress-tag-pro', 180)]
TABS = ['body', 'color', 'pattern', 'eyes', 'nose', 'mouth', 'hats', 'extras', 'backdrop', 'frame']
TAB_PIECE = {'body': 1, 'hats': 2, 'color': 3, 'pattern': 4, 'eyes': 5, 'backdrop': 6, 'frame': 7, 'nose': 8, 'mouth': 9, 'extras': 10}
EXTRA += [(f'tabs-{TAB_PIECE[t]}', f'art-dress-tab-{t}', 144) for t in TABS]
# The title shelf, three slices like the ribbon (the brackets stay at the ends), 72 px tall.
sh = load('shelf-2')
if sh is not None:
    m = sh.width // 2
    ship('art-dress-shelf-l', fit(sh.crop((0, 0, 200, sh.height)), h=72))
    ship('art-dress-shelf-m', fit(sh.crop((m - 4, 0, m + 4, sh.height)), h=72))
    ship('art-dress-shelf-r', fit(sh.crop((sh.width - 200, 0, sh.width, sh.height)), h=72))
EXTRA += [('shelf-1', 'art-dress-title', 900), ('shelf-3', 'art-dress-plaque', 200), ('shelf-4', 'art-dress-lock', 96),
          ('none-1', 'art-dress-none', 120), ('host-1', 'art-dress-bubble', 420), ('host-2', 'art-dress-tag-dressup', 240), ('host-3', 'art-dress-partyhat', 360)]
for src, name, w in EXTRA:
    im = load(src)
    if im is not None:
        ship(name, fit(im, w=w))

ts = os.path.join(REPO, 'apps', 'web', 'lib', 'dress-art.ts')
with open(ts, 'w') as f:
    f.write('// Generated by docs/design/profile-2026-10-05/art/ship.py: the dress-up art (ChatGPT, 10-05) and its real\n')
    f.write('// pixel sizes. Spread into ART_SIZE (art.ts).\n')
    f.write('export type DressArtName = `art-dress-${string}`;\n\n')
    f.write('export const DRESS_ART_SIZE: Record<string, readonly [number, number]> = {\n')
    for k in sorted(SIZES):
        f.write(f"  '{k}': [{SIZES[k][0]}, {SIZES[k][1]}],\n")
    f.write('};\n')
keep = os.path.join(REPO, 'apps', 'android', 'app', 'src', 'main', 'res', 'raw', 'keep_dress.xml')
with open(keep, 'w') as f:
    f.write('<?xml version="1.0" encoding="utf-8"?>\n<!-- The dress-up art (Edit Profile stage, Dressing Room tabs, Title Shelves) is partly looked up by\n'
            '     name (DressArt.tab, getIdentifier); keep it through resource shrinking. -->\n'
            '<resources xmlns:tools="http://schemas.android.com/tools"\n    tools:keep="@drawable/art_dress_*" />\n')
print(len(SIZES), 'shipped:', ', '.join(sorted(SIZES)))
