// Builds the Phase 0 review gallery from the sample JSONs: one page, every
// sample, in the Wordocious look. Output is page CONTENT only (no <html>/<body>)
// so it can be opened locally or published as a private review page.
import fs from 'node:fs';
import path from 'node:path';
import { SAMPLES, readJSON } from './lib.mjs';
const J = (f) => readJSON(path.join(SAMPLES, f));
const rungs = J('rungs.json'), hub = J('hubbub.json'), spy = J('spyglass.json'), dec = J('decipher.json'), kin = J('kindred.json'), cw = J('crosswise.json'), mud = J('muddle.json'), vint = J('muddle-vintage-candidates.json'), scenes = J('muddle-composed-scenes.json').scenes;
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const tiles = (w, cls = '') => `<span class="row">${[...w].map((c) => `<span class="t ${cls}">${esc(c)}</span>`).join('')}</span>`;
const STYLE = 'Single-panel newspaper gag cartoon, confident black ink outlines, flat limited palette on cream paper (#fdf8ec) with purple (#7c3aed) and orange (#f97316) as the only saturated accents and warm greys, one or two characters with expressive faces, generous margins, 4:3. No text, lettering, captions, signage or speech bubbles anywhere in the image.';

const secRungs = rungs.puzzles.map((p) => `<div class="card"><div class="meta">Par ${p.par} · ${p.routes} shortest routes</div><div class="ladder">${p.path.map((w, i) => tiles(w, i === 0 || i === p.path.length - 1 ? 'on' : 'ghost')).join('')}</div></div>`).join('');
const secHub = hub.puzzles.map((p) => `<div class="card"><div class="hubrow"><div class="cluster">${[...p.letters].map((c, i) => `<span class="t ${i === 0 ? 'hubc' : ''}">${c}</span>`).join('')}</div><div><div class="meta">${p.words.length} words · max ${p.max} · solved at ${p.ranks[6].points} pts</div><div class="pang">Pangram: ${p.pangrams.join(', ')}</div></div></div><details><summary>Word list and bonus words</summary><p class="words">${p.words.join(' · ')}</p><p class="words dim">Bonus (accepted, 0 pts): ${p.bonus.join(' · ') || 'none'}</p></details></div>`).join('');
const secSpy = spy.puzzles.map((p) => { const found = new Set(); const D = { E: [0, 1], S: [1, 0], SE: [1, 1], NE: [-1, 1] }; for (const w of p.words) for (let k = 0; k < w.w.length; k++) found.add((w.r + D[w.d][0] * k) * 10 + w.c + D[w.d][1] * k);
  return `<div class="card"><div class="ttl">${esc(p.title)}</div><div class="ws">${[...p.grid].map((c, i) => `<span class="${found.has(i) ? 'hit' : ''}">${c}</span>`).join('')}</div><p class="words">${p.words.map((w) => w.w).join(' · ')}</p><div class="meta">Answer cells tinted here for review only</div></div>`; }).join('');
const secDec = dec.puzzles.map((p) => { const giv = new Set(p.given || []); const T = p.text.toUpperCase(); let k = 0;
  const words = p.cipher.split(' ').map((cwd) => { const cells = [...cwd].map((c) => { const pl = T[k++]; return /[A-Z]/.test(c) ? `<span class="cl${giv.has(pl) ? ' giv' : ''}"><b>${giv.has(pl) ? pl : ''}</b><i>${c}</i></span>` : `<span class="pn">${esc(c)}</span>`; }).join(''); k++; return `<span class="cword">${cells}</span>`; }).join('');
  return `<div class="card"><div class="cgram">${words}</div><div class="meta">Given at the start: ${(p.given || []).join(' ') || 'none'} · ${p.text.length} characters · ${p.distinctLetters} letters</div><details><summary>Answer</summary><p class="plain">${esc(p.text)}</p>${p.author ? `<div class="meta">${esc(p.author)}, ${esc(p.source)}</div>` : ''}</details></div>`; }).join('');
const secKin = kin.puzzles.map((p) => `<div class="card">${p.groups.map((g) => `<div class="grp g${g.tier}"><span class="pips">${'●'.repeat(g.tier)}</span><b>${esc(g.label)}</b><span>${g.words.join(', ')}</span></div>`).join('')}<div class="meta">Traps: ${esc(p.redHerrings)} · validator: ${p.solutions === 1 ? 'exactly one solution' : p.solutions + ' solutions'}</div></div>`).join('');
const secCw = cw.puzzles.map((p) => { const g = Array.from({ length: p.h }, () => Array(p.w).fill(null)), th = {}, num = {}; for (const e of p.entries) { num[e.r * 100 + e.c] = e.n; for (let k = 0; k < e.answer.length; k++) { const r = e.r + (e.dir === 'D' ? k : 0), c = e.c + (e.dir === 'A' ? k : 0); g[r][c] = e.answer[k]; if (e.onTheme) th[r * 100 + c] = true; } }
  const grid = `<div class="cw" style="grid-template-columns:repeat(${p.w},1fr)">${g.flatMap((row, r) => row.map((c, cc) => c ? `<span class="c ${th[r * 100 + cc] ? 'th' : 'gn'}">${num[r * 100 + cc] ? `<i>${num[r * 100 + cc]}</i>` : ''}${c}</span>` : '<span></span>')).join('')}</div>`;
  const clues = (d) => p.entries.filter((e) => e.dir === d).map((e) => `<li><b class="nb ${e.onTheme ? 'th' : 'gn'}">${e.n}</b><span>${esc(e.clue)}</span></li>`).join('');
  const nTh = p.entries.filter((e) => e.onTheme).length;
  return `<div class="card wide"><div class="ttl">${esc(p.title)} <span class="meta">${p.entries.length} entries · ${p.crossings} crossings · ${p.w}×${p.h}</span></div><div class="legend"><span><b class="sw th"></b>Purple = today's theme, ${esc(p.title)} (${nTh})</span><span><b class="sw gn"></b>Amber = any saying (${p.entries.length - nTh})</span></div><div class="cwwrap">${grid}<div class="clues"><h4>Across</h4><ul>${clues('A')}</ul><h4>Down</h4><ul>${clues('D')}</ul></div></div><div class="meta">Answers shown filled in for review</div></div>`; }).join('');
const secMud = mud.puzzles.map((p) => `<div class="card wide"><div class="mudwrap"><div class="art">${scenes[p.id] || '<div class="noart">No composed scene in this sample round</div>'}<p class="cap">${esc(p.caption)}</p></div><div><div class="meta">Scrambles</div><div class="mgrid">${p.words.map((w) => { const pad = '<span class="t void"></span>'.repeat(6 - w.answer.length); return `${[...w.scramble].map((c) => `<span class="t ghost">${esc(c)}</span>`).join('')}${pad}<span class="arrow">→</span>${[...w.answer].map((c, i) => `<span class="t on ${w.circled.includes(i) ? 'ring' : ''}">${c}</span>`).join('')}${pad}`; }).join('')}</div><div class="meta" style="margin-top:10px">Final answer (${p.final.pattern.join(', ')})</div><div class="row">${p.final.answer.split(' ').map((w) => tiles(w, 'gold')).join('<span class="gap"></span>')}</div><details><summary>AI prompt for this cartoon</summary><p class="prompt">${esc(STYLE)} Scene: ${esc(p.scene)}</p></details></div></div></div>`).join('');
const secVint = vint.candidates.map((c) => `<li><a href="${esc(c.page)}">${esc(c.title.replace(/^File:/, '').slice(0, 80))}</a> <span class="meta">${c.year} · ${esc(c.licence)} · ${esc(c.category)}</span></li>`).join('');

const html = `<title>More Games Samples</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800;900&display=swap">
<style>
:root{--th-bg:#ede9fe;--th-bd:#c4b5fd;--th-tx:#5b21b6;--bg:#f8f7ff;--surface:#fff;--border:#ede9f6;--border2:#e0daf0;--text:#1a1a2e;--muted:#6b7280;--faint:#9ca3af;--purple:#7c3aed;--gold-bg:#fffbeb;--gold-bd:#fde68a;--gold-tx:#b45309;--tile:#fff;--paper:#fdf8ec}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#1a1a2e;--surface:#252542;--border:#3a3a5c;--border2:#3a3a5c;--text:#f0eef6;--muted:#a0a0b8;--faint:#8b8ba7;--purple:#a78bfa;--gold-bg:#422006;--gold-bd:#854d0e;--gold-tx:#fcd34d;--tile:#2e2e4a;--th-bg:#3b2a6b;--th-bd:#6d4fc2;--th-tx:#ddd6fe}}
:root[data-theme="dark"]{--bg:#1a1a2e;--surface:#252542;--border:#3a3a5c;--border2:#3a3a5c;--text:#f0eef6;--muted:#a0a0b8;--faint:#8b8ba7;--purple:#a78bfa;--gold-bg:#422006;--gold-bd:#854d0e;--gold-tx:#fcd34d;--tile:#2e2e4a;--th-bg:#3b2a6b;--th-bd:#6d4fc2;--th-tx:#ddd6fe}
body{background:var(--bg);color:var(--text);font-family:'Nunito',system-ui,sans-serif;font-weight:600;font-size:15px;line-height:1.5;padding-inline:16px;padding-block:24px 64px}
main{max-width:1040px;margin:0 auto;display:flex;flex-direction:column;gap:40px}
h1{font-weight:900;font-size:30px;margin:0;color:var(--purple);letter-spacing:.5px;text-wrap:balance}
h2{font-weight:900;font-size:22px;margin:0 0 2px;letter-spacing:.3px}h4{margin:8px 0 2px;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:var(--faint)}
.lede{max-width:68ch;color:var(--muted);margin:6px 0 0}.kick{font-size:12px;font-weight:900;letter-spacing:1.5px;text-transform:uppercase}
.how{color:var(--muted);max-width:72ch;margin:4px 0 14px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:12px}
.card{background:var(--surface);border:1.5px solid var(--border);border-radius:16px;padding:14px;display:flex;flex-direction:column;gap:8px;min-width:0}.wide{grid-column:1/-1}
.meta{font-size:12px;color:var(--faint);font-weight:700}.ttl{font-weight:900;font-size:16px}.dim{color:var(--faint)}
.row{display:inline-flex;gap:3px;flex-wrap:wrap}.t{width:26px;height:26px;border-radius:7px;border:2px solid var(--border2);background:var(--tile);display:inline-flex;align-items:center;justify-content:center;font-weight:900;font-size:13px}
.t.on{background:#7c3aed;border-color:#7c3aed;color:#fff}.t.ghost{color:var(--text)}.t.ring{outline:2.5px solid #f97316;outline-offset:-1px}.t.gold{background:var(--gold-bg);border-color:var(--gold-bd);color:var(--gold-tx)}.t.hubc{background:#c026d3;border-color:#c026d3;color:#fff}
.gap{display:inline-block;width:10px}.ladder{display:flex;flex-direction:column;gap:4px}.hubrow{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.cluster{display:flex;gap:3px}.pang{font-weight:900;color:#c026d3}
.words{margin:6px 0 0;font-size:13px;overflow-wrap:anywhere}details summary{cursor:pointer;font-size:13px;font-weight:800;color:var(--purple)}details summary:focus-visible,a:focus-visible{outline:2px solid var(--purple);outline-offset:2px}
.ws{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;max-width:300px}.ws span{aspect-ratio:1;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:13px;border-radius:5px}.ws .hit{background:#4d7c0f26;color:var(--text)}
.cgram{display:flex;flex-wrap:wrap;gap:8px 12px}.cword{display:inline-flex;gap:2px;align-items:flex-end}.cl{display:inline-flex;flex-direction:column;align-items:center;width:17px}.cl b{width:100%;height:21px;border-bottom:2px solid var(--border2);font-weight:900;font-size:15px;text-align:center;line-height:20px}.cl.giv b{color:#92400e;border-color:#92400e}.cl i{font-style:normal;font-size:10px;font-weight:800;color:var(--faint);font-family:ui-monospace,Menlo,monospace}.pn{font-weight:900;padding-bottom:13px}.plain{margin:6px 0 2px}
.grp{display:flex;flex-wrap:wrap;gap:6px;align-items:baseline;border-radius:10px;padding:7px 10px;font-size:13px}.grp b{font-weight:900}.pips{font-size:8px;letter-spacing:2px}
.g1{background:#ddd6fe;color:#1a1a2e}.g2{background:#a78bfa;color:#1a1a2e}.g3{background:#7c3aed;color:#fff}.g4{background:#1a1a2e;color:#fff;border:1.5px solid #4c4c6e}
.cwwrap{display:flex;gap:18px;flex-wrap:wrap;align-items:flex-start}.cw{display:grid;gap:2px;width:min(100%,320px)}.cw span{aspect-ratio:1}.cw .c{position:relative;border:1.5px solid;border-radius:6px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:13px}.cw i{position:absolute;top:0;left:2px;font-size:8px;font-style:normal;opacity:.75}.th{background:var(--th-bg);border-color:var(--th-bd);color:var(--th-tx)}.gn{background:var(--gold-bg);border-color:var(--gold-bd);color:var(--gold-tx)}
.legend{display:flex;flex-wrap:wrap;gap:6px 18px;font-size:13px;font-weight:800}.legend span{display:inline-flex;align-items:center;gap:6px}.sw{width:14px;height:14px;border-radius:4px;border:1.5px solid;display:inline-block}
.clues{flex:1;min-width:240px}.clues ul{list-style:none;margin:0;padding:0;font-size:13px;display:flex;flex-direction:column;gap:4px}.clues li{display:flex;gap:8px;align-items:baseline}.nb{flex:none;min-width:22px;text-align:center;border:1.5px solid;border-radius:6px;font-size:11px;font-weight:900;padding:0 3px;font-variant-numeric:tabular-nums}
.mudwrap{display:flex;gap:20px;flex-wrap:wrap}.art{flex:0 1 300px;min-width:240px}.art svg{width:100%;height:auto;border-radius:12px;border:1.5px solid var(--border);display:block}.noart{aspect-ratio:4/3;border:1.5px dashed var(--border2);border-radius:12px;display:flex;align-items:center;justify-content:center;color:var(--faint);font-size:13px;text-align:center;padding:12px}
.cap{font-weight:800;text-align:center;margin:8px 4px 0}.mgrid{--ts:26px;display:grid;grid-template-columns:repeat(6,var(--ts)) 18px repeat(6,var(--ts));gap:5px 3px;align-items:center;margin:4px 0}.mgrid .t{width:var(--ts);height:var(--ts)}.t.void{visibility:hidden}.arrow{color:var(--faint);text-align:center}@media (max-width:480px){.mgrid{--ts:22px}}.prompt{font-size:13px;color:var(--muted);margin:6px 0 0}
.vint{margin:0;padding-left:18px;font-size:13px;display:flex;flex-direction:column;gap:4px}a{color:var(--purple)}.note{background:var(--gold-bg);border:1.5px solid var(--gold-bd);color:var(--gold-tx);border-radius:12px;padding:10px 14px;font-size:13px;font-weight:700;max-width:80ch}
</style>
<main>
<header><div class="kick" style="color:#4f46e5">Wordocious · More Games · Phase 0</div><h1>Sample puzzles for your verdict</h1><p class="lede">Every puzzle below was produced by the real authoring tools and passed its validator. Nothing here touches the apps. For each game decide: go, adjust or drop.</p></header>
<section><div class="kick" style="color:#0284c7">Rungs · word ladder</div><h2>${rungs.puzzles.length} ladders from ${rungs.totalQualifying.toLocaleString()} that qualify</h2><p class="how">Change one letter at a time. Both ends are everyday answer words, every ladder has at least two shortest routes through common words, and no obscure word can beat par. Fully generated, nothing to review long term.</p><div class="grid">${secRungs}</div></section>
<section><div class="kick" style="color:#c026d3">Hubbub · seven-letter hub</div><h2>${hub.puzzles.length} letter sets from ${hub.qualifying.toLocaleString()} that qualify</h2><p class="how">The filled tile is the required centre letter. Scoring words come from the friendly common tier; rarer real words are accepted as zero-point bonus words. No letter set contains S.</p><div class="grid">${secHub}</div></section>
<section><div class="kick" style="color:#4d7c0f">Spyglass · word search</div><h2>${spy.puzzles.length} themed grids</h2><p class="how">Ten words per grid, only forwards: across, down and the two rightward diagonals. Filler letters are rerolled until no list word appears twice and no line spells a blocked term.</p><div class="grid">${secSpy}</div></section>
<section><div class="kick" style="color:#92400e">Decipher · cryptogram</div><h2>${dec.puzzles.length} everyday sayings, three letters given</h2><p class="how">Round two, after your note that quotations were too hard. Same cipher rules, but the text is a saying everyone can finish from a few letters, it is shorter, and the three most common letters are filled in from the start. The small letter under each blank is the code letter.</p><div class="grid">${secDec}</div></section>
<section><div class="kick" style="color:#9f1239">Kindred · groups of four</div><h2>${kin.puzzles.length} original puzzles</h2><p class="how">Shown solved. The bars use the single-hue ramp with pips, lightest is easiest. The validator proves each puzzle has exactly one solution even with its traps.</p><div class="grid">${secKin}</div></section>
<section><div class="kick" style="color:#475569">Crosswise · sayings crossword</div><h2>${cw.puzzles.length} grids from ${cw.accepted} screened sayings</h2><p class="how">Every clue is a familiar saying with a blank. At least 60% of entries are on the puzzle's theme. Colour does the labelling: one legend line per puzzle, purple for theme entries, amber for the rest, on both the grid and the clue numbers. No answer can be read in another clue of the same puzzle.</p><div class="grid">${secCw}</div></section>
<section><div class="kick" style="color:#f97316">Muddle · cartoon scramble</div><h2>${mud.puzzles.length} complete puzzles, and the cartoon three ways</h2><p class="how">Ringed letters are the circled ones; together they spell the final answer exactly. Every scramble starts in the same column and every answer row starts in the same column, whether the word has five letters or six. Each card shows the composed-scene route where one was drawn, and holds the ready-to-paste AI prompt. Vintage candidates follow.</p><div class="grid">${secMud}</div>
<h4 style="margin-top:22px">Vintage public-domain route: what the search found</h4><p class="note">Honest result: Wikimedia's public-domain cartoons are mostly political satire, not domestic gag panels. Only ${vint.candidates.length} of the files collected passed the first screen, and few would suit a family word game. More exist inside scanned issues of Judge and Life at the Library of Congress and Internet Archive, but each panel would need cropping from a page scan by hand.</p><ul class="vint">${secVint}</ul></section>
</main>`;
const out = path.join(SAMPLES, 'index.html'); fs.writeFileSync(out, html); console.log('wrote', out, Math.round(html.length / 1024), 'KB');
