// Builds the Phase 0 review gallery from the sample JSONs: one page, every
// sample, in the Wordocious look. Output is page CONTENT only (no <html>/<body>)
// so it can be opened locally or published as a private review page.
import fs from 'node:fs';
import path from 'node:path';
import { SAMPLES, readJSON } from './lib.mjs';
const J = (f) => readJSON(path.join(SAMPLES, f));
const rungs = J('rungs.json'), hub = J('hubbub.json'), spy = J('spyglass.json'), dec = J('decipher.json'), kin = J('kindred.json'), cw = J('crosswise.json'), mud = J('muddle.json'), vint = J('muddle-vintage-candidates.json'), scenes = J('muddle-composed-scenes.json').scenes;
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const tiles = (w, cls = '') => `<span class="row">${[...w].map((c) => `<span class="t ${cls}">${esc(c)}</span>`).join('')}</span>`;
const STYLE = 'Single-panel newspaper gag cartoon, confident black ink outlines, flat limited palette on cream paper (#fdf8ec) with purple (#7c3aed) and orange (#f97316) as the only saturated accents and warm greys, one or two characters with expressive faces, generous margins, 4:3. No text, lettering, captions, signage or speech bubbles anywhere in the image.';

const secRungs = rungs.puzzles.map((p) => `<div class="card"><div class="meta">Par ${p.par} · ${p.routes} shortest routes</div><div class="ladder">${p.path.map((w, i) => tiles(w, i === 0 || i === p.path.length - 1 ? 'on' : 'ghost')).join('')}</div></div>`).join('');
const secHub = hub.puzzles.map((p) => `<div class="card"><div class="hubrow"><div class="cluster">${[...p.letters].map((c, i) => `<span class="t ${i === 0 ? 'hubc' : ''}">${c}</span>`).join('')}</div><div><div class="meta">${p.words.length} words · max ${p.max} · solved at ${p.ranks[6].points} pts</div><div class="pang">Pangram: ${p.pangrams.join(', ')}</div></div></div><details><summary>Word list and bonus words</summary><p class="words">${p.words.join(' · ')}</p><p class="words dim">Bonus (accepted, 0 pts): ${p.bonus.join(' · ') || 'none'}</p></details></div>`).join('');
const secSpy = spy.puzzles.map((p) => { const found = new Set(); const D = { E: [0, 1], S: [1, 0], SE: [1, 1], NE: [-1, 1] }; for (const w of p.words) for (let k = 0; k < w.w.length; k++) found.add((w.r + D[w.d][0] * k) * 10 + w.c + D[w.d][1] * k);
  return `<div class="card"><div class="ttl">${esc(p.title)}</div><div class="ws">${[...p.grid].map((c, i) => `<span class="${found.has(i) ? 'hit' : ''}">${c}</span>`).join('')}</div><p class="words">${p.words.map((w) => w.w).join(' · ')}</p><div class="meta">Answer cells tinted here for review only</div></div>`; }).join('');
const secDec = dec.puzzles.map((p) => `<div class="card"><p class="cipher">${esc(p.cipher)}</p><details><summary>Answer and source</summary><p class="plain">${esc(p.text)}</p><div class="meta">${esc(p.author)}, ${esc(p.source)} · ${p.text.length} characters · ${p.distinctLetters} letters · source not yet verified against a primary text</div></details></div>`).join('');
const secKin = kin.puzzles.map((p) => `<div class="card">${p.groups.map((g) => `<div class="grp g${g.tier}"><span class="pips">${'●'.repeat(g.tier)}</span><b>${esc(g.label)}</b><span>${g.words.join(', ')}</span></div>`).join('')}<div class="meta">Traps: ${esc(p.redHerrings)} · validator: ${p.solutions === 1 ? 'exactly one solution' : p.solutions + ' solutions'}</div></div>`).join('');
const secCw = cw.puzzles.map((p) => { const g = Array.from({ length: p.h }, () => Array(p.w).fill(null)), num = {}; for (const e of p.entries) { num[e.r * 100 + e.c] = e.n; for (let k = 0; k < e.answer.length; k++) g[e.r + (e.dir === 'D' ? k : 0)][e.c + (e.dir === 'A' ? k : 0)] = e.answer[k]; }
  const grid = `<div class="cw" style="grid-template-columns:repeat(${p.w},1fr)">${g.flatMap((row, r) => row.map((c, cc) => c ? `<span class="c">${num[r * 100 + cc] ? `<i>${num[r * 100 + cc]}</i>` : ''}${c}</span>` : '<span></span>')).join('')}</div>`;
  const clues = (d) => p.entries.filter((e) => e.dir === d).map((e) => `<li><b>${e.n}.</b> ${esc(e.clue)}${e.onTheme ? '' : ' <em>(wildcard)</em>'}</li>`).join('');
  return `<div class="card wide"><div class="ttl">${esc(p.title)} <span class="meta">${p.entries.length} entries · ${p.crossings} crossings · ${p.w}×${p.h}</span></div><div class="cwwrap">${grid}<div class="clues"><h4>Across</h4><ul>${clues('A')}</ul><h4>Down</h4><ul>${clues('D')}</ul></div></div><div class="meta">Answers shown filled in for review</div></div>`; }).join('');
const secMud = mud.puzzles.map((p) => `<div class="card wide"><div class="mudwrap"><div class="art">${scenes[p.id] || '<div class="noart">No composed scene in this sample round</div>'}<p class="cap">${esc(p.caption)}</p></div><div><div class="meta">Scrambles</div>${p.words.map((w) => `<div class="mrow">${tiles(w.scramble, 'ghost')}<span class="arrow">→</span><span class="row">${[...w.answer].map((c, i) => `<span class="t on ${w.circled.includes(i) ? 'ring' : ''}">${c}</span>`).join('')}</span></div>`).join('')}<div class="meta" style="margin-top:10px">Final answer (${p.final.pattern.join(', ')})</div><div class="row">${p.final.answer.split(' ').map((w) => tiles(w, 'gold')).join('<span class="gap"></span>')}</div><details><summary>AI prompt for this cartoon</summary><p class="prompt">${esc(STYLE)} Scene: ${esc(p.scene)}</p></details></div></div></div>`).join('');
const secVint = vint.candidates.map((c) => `<li><a href="${esc(c.page)}">${esc(c.title.replace(/^File:/, '').slice(0, 80))}</a> <span class="meta">${c.year} · ${esc(c.licence)} · ${esc(c.category)}</span></li>`).join('');

const html = `<title>More Games Samples</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800;900&display=swap">
<style>
:root{--bg:#f8f7ff;--surface:#fff;--border:#ede9f6;--border2:#e0daf0;--text:#1a1a2e;--muted:#6b7280;--faint:#9ca3af;--purple:#7c3aed;--gold-bg:#fffbeb;--gold-bd:#fde68a;--gold-tx:#b45309;--tile:#fff;--paper:#fdf8ec}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){--bg:#1a1a2e;--surface:#252542;--border:#3a3a5c;--border2:#3a3a5c;--text:#f0eef6;--muted:#a0a0b8;--faint:#8b8ba7;--purple:#a78bfa;--gold-bg:#422006;--gold-bd:#854d0e;--gold-tx:#fcd34d;--tile:#2e2e4a}}
:root[data-theme="dark"]{--bg:#1a1a2e;--surface:#252542;--border:#3a3a5c;--border2:#3a3a5c;--text:#f0eef6;--muted:#a0a0b8;--faint:#8b8ba7;--purple:#a78bfa;--gold-bg:#422006;--gold-bd:#854d0e;--gold-tx:#fcd34d;--tile:#2e2e4a}
body{background:var(--bg);color:var(--text);font-family:'Nunito',system-ui,sans-serif;font-weight:600;font-size:15px;line-height:1.5;padding-inline:16px;padding-block:24px 64px}
main{max-width:1040px;margin:0 auto;display:flex;flex-direction:column;gap:40px}
h1{font-weight:900;font-size:30px;margin:0;color:var(--purple);letter-spacing:.5px;text-wrap:balance}
h2{font-weight:900;font-size:22px;margin:0 0 2px;letter-spacing:.3px}h4{margin:8px 0 2px;font-size:12px;letter-spacing:1px;text-transform:uppercase;color:var(--faint)}
.lede{max-width:68ch;color:var(--muted);margin:6px 0 0}.kick{font-size:12px;font-weight:900;letter-spacing:1.5px;text-transform:uppercase}
.how{color:var(--muted);max-width:72ch;margin:4px 0 14px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:12px}
.card{background:var(--surface);border:1.5px solid var(--border);border-radius:16px;padding:14px;display:flex;flex-direction:column;gap:8px;min-width:0}.wide{grid-column:1/-1}
.meta{font-size:12px;color:var(--faint);font-weight:700}.ttl{font-weight:900;font-size:16px}.dim{color:var(--faint)}
.row{display:inline-flex;gap:3px;flex-wrap:wrap}.t{width:26px;height:26px;border-radius:7px;border:2px solid var(--border2);background:var(--tile);display:inline-flex;align-items:center;justify-content:center;font-weight:900;font-size:13px}
.t.on{background:#7c3aed;border-color:#7c3aed;color:#fff}.t.ghost{color:var(--text)}.t.ring{outline:2.5px solid #f97316;outline-offset:-1px}.t.gold{background:var(--gold-bg);border-color:var(--gold-bd);color:var(--gold-tx)}.t.hubc{background:#c026d3;border-color:#c026d3;color:#fff}
.gap{display:inline-block;width:10px}.ladder{display:flex;flex-direction:column;gap:4px}.hubrow{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.cluster{display:flex;gap:3px}.pang{font-weight:900;color:#c026d3}
.words{margin:6px 0 0;font-size:13px;overflow-wrap:anywhere}details summary{cursor:pointer;font-size:13px;font-weight:800;color:var(--purple)}details summary:focus-visible,a:focus-visible{outline:2px solid var(--purple);outline-offset:2px}
.ws{display:grid;grid-template-columns:repeat(10,1fr);gap:2px;max-width:300px}.ws span{aspect-ratio:1;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:13px;border-radius:5px}.ws .hit{background:#4d7c0f26;color:var(--text)}
.cipher{font-family:ui-monospace,Menlo,monospace;font-weight:700;letter-spacing:1px;margin:0;overflow-wrap:anywhere}.plain{margin:6px 0 2px}
.grp{display:flex;flex-wrap:wrap;gap:6px;align-items:baseline;border-radius:10px;padding:7px 10px;font-size:13px}.grp b{font-weight:900}.pips{font-size:8px;letter-spacing:2px}
.g1{background:#ddd6fe;color:#1a1a2e}.g2{background:#a78bfa;color:#1a1a2e}.g3{background:#7c3aed;color:#fff}.g4{background:#1a1a2e;color:#fff;border:1.5px solid #4c4c6e}
.cwwrap{display:flex;gap:18px;flex-wrap:wrap;align-items:flex-start}.cw{display:grid;gap:2px;width:min(100%,320px)}.cw span{aspect-ratio:1}.cw .c{position:relative;background:var(--tile);border:1.5px solid var(--border2);border-radius:5px;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:13px}.cw i{position:absolute;top:0;left:2px;font-size:8px;font-style:normal;color:var(--faint)}
.clues{flex:1;min-width:240px}.clues ul{list-style:none;margin:0;padding:0;font-size:13px;display:flex;flex-direction:column;gap:2px}.clues em{color:var(--faint);font-style:normal;font-size:11px}
.mudwrap{display:flex;gap:20px;flex-wrap:wrap}.art{flex:0 1 300px;min-width:240px}.art svg{width:100%;height:auto;border-radius:12px;border:1.5px solid var(--border);display:block}.noart{aspect-ratio:4/3;border:1.5px dashed var(--border2);border-radius:12px;display:flex;align-items:center;justify-content:center;color:var(--faint);font-size:13px;text-align:center;padding:12px}
.cap{font-weight:800;text-align:center;margin:8px 4px 0}.mrow{display:flex;align-items:center;gap:8px;margin:4px 0;flex-wrap:wrap}.arrow{color:var(--faint)}.prompt{font-size:13px;color:var(--muted);margin:6px 0 0}
.vint{margin:0;padding-left:18px;font-size:13px;display:flex;flex-direction:column;gap:4px}a{color:var(--purple)}.note{background:var(--gold-bg);border:1.5px solid var(--gold-bd);color:var(--gold-tx);border-radius:12px;padding:10px 14px;font-size:13px;font-weight:700;max-width:80ch}
</style>
<main>
<header><div class="kick" style="color:#4f46e5">Wordocious · More Games · Phase 0</div><h1>Sample puzzles for your verdict</h1><p class="lede">Every puzzle below was produced by the real authoring tools and passed its validator. Nothing here touches the apps. For each game decide: go, adjust or drop.</p></header>
<section><div class="kick" style="color:#0284c7">Rungs · word ladder</div><h2>${rungs.puzzles.length} ladders from ${rungs.totalQualifying.toLocaleString()} that qualify</h2><p class="how">Change one letter at a time. Both ends are everyday answer words, every ladder has at least two shortest routes through common words, and no obscure word can beat par. Fully generated, nothing to review long term.</p><div class="grid">${secRungs}</div></section>
<section><div class="kick" style="color:#c026d3">Hubbub · seven-letter hub</div><h2>${hub.puzzles.length} letter sets from ${hub.qualifying.toLocaleString()} that qualify</h2><p class="how">The filled tile is the required centre letter. Scoring words come from the friendly common tier; rarer real words are accepted as zero-point bonus words. No letter set contains S.</p><div class="grid">${secHub}</div></section>
<section><div class="kick" style="color:#4d7c0f">Spyglass · word search</div><h2>${spy.puzzles.length} themed grids</h2><p class="how">Ten words per grid, only forwards: across, down and the two rightward diagonals. Filler letters are rerolled until no list word appears twice and no line spells a blocked term.</p><div class="grid">${secSpy}</div></section>
<section><div class="kick" style="color:#92400e">Decipher · cryptogram</div><h2>${dec.puzzles.length} public-domain quotations</h2><p class="how">All authors died before 1951. Each line is what the player sees; open a card for the answer and source. Every source still needs checking against a primary text before it could ship.</p><div class="grid">${secDec}</div></section>
<section><div class="kick" style="color:#9f1239">Kindred · groups of four</div><h2>${kin.puzzles.length} original puzzles</h2><p class="how">Shown solved. The bars use the single-hue ramp with pips, lightest is easiest. The validator proves each puzzle has exactly one solution even with its traps.</p><div class="grid">${secKin}</div></section>
<section><div class="kick" style="color:#475569">Crosswise · sayings crossword</div><h2>${cw.puzzles.length} grids from ${cw.accepted} screened sayings</h2><p class="how">Every clue is a familiar saying with a blank. At least 60% of entries are on the puzzle's theme and the rest are marked wildcard. No answer can be read in another clue of the same puzzle.</p><div class="grid">${secCw}</div></section>
<section><div class="kick" style="color:#f97316">Muddle · cartoon scramble</div><h2>${mud.puzzles.length} complete puzzles, and the cartoon three ways</h2><p class="how">Ringed letters are the circled ones; together they spell the final answer exactly. Each card shows the composed-scene route where one was drawn, and holds the ready-to-paste AI prompt. Vintage candidates follow.</p><div class="grid">${secMud}</div>
<h4 style="margin-top:22px">Vintage public-domain route: what the search found</h4><p class="note">Honest result: Wikimedia's public-domain cartoons are mostly political satire, not domestic gag panels. Only ${vint.candidates.length} of the files collected passed the first screen, and few would suit a family word game. More exist inside scanned issues of Judge and Life at the Library of Congress and Internet Archive, but each panel would need cropping from a page scan by hand.</p><ul class="vint">${secVint}</ul></section>
</main>`;
const out = path.join(SAMPLES, 'index.html'); fs.writeFileSync(out, html); console.log('wrote', out, Math.round(html.length / 1024), 'KB');
