// Static mockups of where the More Games live in the existing app chrome:
// Home, the More Games sheet, the Daily leaderboard, Records and Profile stats.
// Drawn from the real components' measurements (app/page.tsx mode card,
// components/profile/mode-picker.tsx, app/daily, app/records, mode-detail-panel)
// so the founder can picture the integration before any app code exists.
const ic = (d, fill = false) => `<svg viewBox="0 0 24 24" fill="${fill ? 'currentColor' : 'none'}" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const I = {
  grid: ic('<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>'),
  sudoku: ic('<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18M15 3v18"/>'),
  shuffle: ic('<path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.7-1.1 2-1.7 3.3-1.7H22"/><path d="m18 2 4 4-4 4"/><path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2"/><path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8"/><path d="m18 14 4 4-4 4"/>'),
  hex: ic('<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>'),
  cross: ic('<rect x="9" y="2.5" width="6" height="6" rx="1"/><rect x="2.5" y="9" width="6" height="6" rx="1"/><rect x="9" y="9" width="6" height="6" rx="1"/><rect x="15.500" y="9" width="6" height="6" rx="1"/><rect x="9" y="15.500" width="6" height="6" rx="1"/>'),
  four: ic('<circle cx="7.5" cy="7.5" r="3.2"/><circle cx="16.5" cy="7.5" r="3.2"/><circle cx="7.5" cy="16.5" r="3.2"/><circle cx="16.5" cy="16.5" r="3.2"/>'),
  ladder: ic('<path d="M8 3v18M16 3v18M8 7h8M8 12h8M8 17h8"/>'),
  key: ic('<circle cx="8" cy="15" r="4.5"/><path d="m11.500 11.500 8.500-8.500M17 6l3 3M14.500 8.500l2 2"/>'),
  search: ic('<circle cx="11" cy="11" r="7"/><path d="m20.500 20.500-4.200-4.200"/>'),
  crown: ic('<path d="M3 18h18l-1.500-10.500-4.500 4L12 4.500 9 11.500l-4.500-4z"/>'),
  star: ic('<path d="m12 2.500 2.900 6 6.600.900-4.800 4.600 1.200 6.500L12 17.400 6.100 20.500l1.200-6.500L2.500 9.400l6.600-.900z"/>', true),
  broom: ic('<path d="m13 11 8-8M9.500 9.500l5 5M4 20c1-4 3-7 6.500-9.500l3 3C11 17 8 19 4 20z"/>'),
  more: ic('<circle cx="5" cy="12" r="1.600"/><circle cx="12" cy="12" r="1.600"/><circle cx="19" cy="12" r="1.600"/>', true),
  clock: ic('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'), target: ic('<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>'),
  zap: ic('<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>'), trophy: ic('<path d="M8 21h8M12 17v4M7 4h10v5a5 5 0 0 1-10 0zM7 6H4v2a3 3 0 0 0 3 3M17 6h3v2a3 3 0 0 1-3 3"/>'),
};
const fixSvg = (s) => s.replace(/(\d)\.(\d)00\b/g, '$1.$2'); // tidy "1.500" → "1.5" in hand-typed paths

const CORE = [['Classic', '#7c3aed', 'W', '4 guesses · 38s', 'W'], ['VS Battle', '#0d9488', '⚔', 'Real-time PvP', ''], ['QuadWord', '#ec4899', 'IV', '7 guesses · 2:10', 'W'], ['OctoWord', '#7e22ce', 'VIII', '8 boards, 13 tries', ''], ['Succession', '#2563eb', '↗', '4 words, one by one', ''], ['Deliverance', '#059669', '⛨', '4 prefilled boards', ''], ['Six', '#06b6d4', '6', '6 letters, 7 tries', ''], ['Seven', '#84cc16', '7', '7 letters, 8 tries', ''], ['Gauntlet', '#d97706', '☠', '5 escalating stages', '']];
const MORE = { Word: [['Muddle', '#f97316', I.shuffle, 'Unscramble the punchline', 'W', '5 checks · 1:52'], ['Rungs', '#0284c7', I.ladder, 'One letter at a time', '', ''], ['Spyglass', '#4d7c0f', I.search, 'Themed word search', '', ''], ['Hubbub', '#c026d3', I.hex, 'Seven letters, one hub', '', '']], Trivia: [['ProperNoundle', '#dc2626', I.crown, 'Guess famous names', '', ''], ['Crosswordocious', '#475569', I.cross, 'Fill-in sayings crossword', '', '']], Logic: [['Sudoku', '#1e40af', I.sudoku, 'Daily number logic', 'W', '0 mistakes · 6:41'], ['Kindred', '#9f1239', I.four, 'Four groups of four', '', ''], ['Decipher', '#92400e', I.key, 'Crack the coded saying', '', '']] };

const card = (t, a, icon, sub, pill) => `<div class="mc" style="--a:${a}${pill ? `;background:${a}0f;border-color:${a}66` : ''}"><i class="bar"></i><span class="it">${icon}</span><b>${t}</b><small>${sub}</small>${pill ? `<em class="wl">${pill}</em>` : ''}</div>`;
const phone = (title, note, body) => `<figure class="ph"><figcaption><b>${title}</b><span>${note}</span></figcaption><div class="scr">${body}</div></figure>`;

const home = phone('Home', 'ProperNoundle\'s tile becomes More Games. The grid keeps its shape and the sweep says 8.',
  `<div class="hero"><div class="ht">${I.star}<span>Daily Challenge</span>${I.star}</div><small>8 puzzles · Leaderboards &amp; medals</small><small>Resets in 09:14:22</small></div><div class="sec">GAME MODES</div><div class="mg2">${CORE.map(([t, a, g, s, p]) => card(t, a, `<u>${g}</u>`, s, p)).join('')}${card('More Games', '#4f46e5', I.grid, '2 of 9 played today', '')}</div>`);

const sheet = phone('More Games sheet', 'Opens from the tile. The same cards as Home, grouped. Respects Daily / Unlimited and locks.',
  `<div class="grab"></div><div class="sht">MORE GAMES</div>${Object.entries(MORE).map(([k, list]) => `<div class="sec">${k.toUpperCase()}</div><div class="mg2">${list.map(([t, a, icn, s, p, r]) => card(t, a, icn, r || s, p)).join('')}</div>`).join('')}`);

const chip = (l, a, icn, on) => `<span class="pk${on ? ' on' : ''}" style="--a:${a}"><i>${icn}</i>${l}</span>`;
const PICK = [['Classic', '#7c3aed', 'W'], ['Quad', '#ec4899', 'IV'], ['Octo', '#7e22ce', 'VIII'], ['Succ.', '#2563eb', '↗'], ['Deliv.', '#059669', '⛨'], ['Six', '#06b6d4', '6'], ['Seven', '#84cc16', '7'], ['Gauntlet', '#d97706', '☠']];
const picker = `<div class="pick">${PICK.map(([l, a, g]) => chip(l, a, `<u>${g}</u>`)).join('')}${chip('Sweep', '#4f46e5', I.broom)}${chip('More', '#4f46e5', I.more, true)}</div><div class="strip">${[['Sudoku', '#1e40af', I.sudoku, 1], ['Muddle', '#f97316', I.shuffle], ['Hubbub', '#c026d3', I.hex], ['Crossword', '#475569', I.cross], ['Kindred', '#9f1239', I.four], ['Rungs', '#0284c7', I.ladder]].map(([l, a, icn, on]) => chip(l, a, icn, on)).join('')}<span class="fade"></span></div>`;
const rows = [['1', 'oliver_b', '0 mistakes · 3:58', '2,172', ''], ['2', 'wordsmith', '0 mistakes · 4:40', '2,166', ''], ['3', 'brian (you)', '0 mistakes · 6:41', '2,151', 'you'], ['4', 'doug_t', '1 mistake · 5:02', '1,864', ''], ['5', 'ninabee', '1 mistake · 7:30 · 1 hint', '1,745', '']];
const board = phone('Daily leaderboard', 'The eight sweep games and Sweep stay as they are. One More chip opens the other nine.',
  `<div class="pt">DAILY CHALLENGE</div>${picker}<div class="rank">You're ranked <b>#3</b> of 412</div><div class="lb"><div class="lbh"><span>LEADERBOARD</span><span class="seg"><i class="on">All</i><i>Friends</i></span></div>${rows.map(([n, u, d, s, y]) => `<div class="lr${y ? ' you' : ''}"><span class="rk">${n}</span><span class="av">${u[0].toUpperCase()}</span><span class="nm"><b>${u}</b><small>${d} <em>Win</em></small></span><span class="sc">${s}</span></div>`).join('')}</div>`);

const cell = (icn, v, l) => `<div class="stc"><span>${icn}</span><div><b>${v}</b><small>${l}</small></div></div>`;
const records = phone('Records · You', 'Same four cells for every game, with the wording each game needs.',
  `<div class="pt">RECORDS</div><div class="tabs"><i>Daily</i><i>All-Time</i><i class="on">You</i></div><div class="sh2">YOUR BESTS BY MODE</div>${picker}<div class="rc" style="--a:#1e40af"><i class="bar"></i><div class="rch"><span class="it">${I.sudoku}</span><b>Sudoku</b></div><div class="g2s">${cell(I.clock, '3m 58s', 'Fastest Win')}${cell(I.target, '0 mistakes', 'Fewest Mistakes')}${cell(I.zap, '41 games', 'Games Played')}${cell(I.trophy, '36–5', 'Win–Loss')}</div></div><div class="rc" style="--a:#c026d3"><i class="bar"></i><div class="rch"><span class="it">${I.hex}</span><b>Hubbub</b></div><div class="g2s">${cell(I.clock, '2m 10s', 'Fastest to Hubbub')}${cell(I.target, 'Pandemonium', 'Best Rank')}${cell(I.zap, '29 games', 'Games Played')}${cell(I.trophy, '24–5', 'Win–Loss')}</div></div>`);

const stat = (v, l) => `<div><b>${v}</b><small>${l}</small></div>`;
const profile = phone('Profile · Stats', 'The familiar eight cells, then a card of stats that only make sense for that game.',
  `<div class="tabs"><i class="on">Solo</i><i>VS</i><i>VS CPU</i></div><div class="strip">${chip('All', '#7c3aed', I.zap)}${chip('Classic', '#7c3aed', '<u>W</u>')}${chip('Quad', '#ec4899', '<u>IV</u>')}${chip('More', '#4f46e5', I.more, true)}${chip('Sudoku', '#1e40af', I.sudoku, true)}<span class="fade"></span></div><div class="rch" style="--a:#1e40af;margin-top:4px"><span class="it">${I.sudoku}</span><b style="color:#1e40af">Sudoku</b></div><div class="sg">${stat('36', 'Wins')}${stat('5', 'Losses')}${stat('41', 'Games')}${stat('88%', 'Win Rate')}${stat('2,172', 'Best')}${stat('3:58', 'Fastest')}${stat('6', 'Streak')}${stat('14', 'Best Streak')}</div><div class="own" style="--a:#1e40af"><h6>SUDOKU STATS</h6><div class="sg two">${stat('22', 'No-mistake solves')}${stat('0.6', 'Avg mistakes')}${stat('31', 'No-hint solves')}${stat('6:12', 'Avg time')}${stat('9', 'Under 5 minutes')}${stat('4', 'Clean streak')}</div></div><div class="gone">Word-only cards (Most Played Words, Opener Yield, Position Accuracy) are hidden for this game.</div>`);

export const screensHtml = fixSvg(`<div class="phones">${home}${sheet}${board}${records}${profile}</div>`);
export const screensCss = `
.phones{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:22px 18px;align-items:start}.ph{margin:0;display:flex;flex-direction:column;gap:8px;min-width:0}.ph figcaption{display:flex;flex-direction:column;gap:2px}.ph figcaption b{font-weight:900;font-size:15px}.ph figcaption span{font-size:12.5px;color:var(--muted);min-height:36px}
.scr{background:var(--bg);border:1.5px solid var(--border2);border-radius:26px;padding:14px 12px 16px;display:flex;flex-direction:column;gap:8px;box-shadow:0 6px 20px rgba(26,26,46,.06)}.scr svg{width:16px;height:16px;display:block}.scr small{display:block}
.hero{height:80px;border-radius:14px;background:linear-gradient(135deg,#ede9fe,#ddd6fe);border:1.5px solid #a78bfa;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px;color:#6d28d9}.hero small{font-size:10px;font-weight:700}.ht{display:flex;align-items:center;gap:6px;color:#7c3aed}.ht span{font-size:18px;font-weight:900;background:linear-gradient(135deg,#7c3aed,#4f46e5);-webkit-background-clip:text;background-clip:text;color:transparent}
.sec{font-size:10px;font-weight:900;letter-spacing:1.5px;color:var(--faint);margin-top:4px}.mg2{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.mc{position:relative;background:var(--surface);border:1.5px solid var(--border);border-radius:14px;padding:12px;display:flex;flex-direction:column;overflow:hidden;min-width:0}.bar{position:absolute;top:0;left:0;right:0;height:4px;background:linear-gradient(90deg,var(--a),color-mix(in srgb,var(--a) 55%,transparent))}.it{width:32px;height:32px;border-radius:8px;background:color-mix(in srgb,var(--a) 9%,transparent);color:var(--a);display:flex;align-items:center;justify-content:center;margin-bottom:6px;flex:none}.it u{text-decoration:none;font-size:11px;font-weight:900}.mc b{font-size:13px;font-weight:900;overflow-wrap:anywhere}.mc small{font-size:10px;font-weight:700;color:var(--muted);line-height:14px;height:28px;overflow:hidden}.wl{position:absolute;top:10px;right:10px;width:20px;height:20px;border-radius:6px;background:#7c3aed;color:#fff;font-style:normal;font-size:10px;font-weight:900;display:flex;align-items:center;justify-content:center}
.grab{width:40px;height:6px;border-radius:3px;background:var(--border2);margin:0 auto}.sht,.pt{font-weight:900;font-size:20px;letter-spacing:.5px;text-align:center;background:linear-gradient(135deg,#a78bfa,#ec4899);-webkit-background-clip:text;background-clip:text;color:transparent}.sht{background-image:linear-gradient(135deg,#4f46e5,#7c3aed);text-align:left}
.pick{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.strip{position:relative;display:flex;gap:6px;overflow:hidden;padding:8px;border-radius:14px;background:color-mix(in srgb,#4f46e5 6%,transparent);border:1.5px dashed color-mix(in srgb,#4f46e5 35%,transparent)}.strip .pk{flex:none;min-width:54px}.fade{position:absolute;right:0;top:0;bottom:0;width:34px;background:linear-gradient(90deg,transparent,var(--bg))}
.pk{display:flex;flex-direction:column;align-items:center;gap:3px;padding:7px 2px;border-radius:12px;background:var(--surface);border:1.5px solid var(--border);font-size:9.5px;font-weight:800;color:var(--muted);min-width:0}.pk i{width:26px;height:26px;border-radius:8px;background:color-mix(in srgb,var(--a) 9%,transparent);color:var(--a);display:flex;align-items:center;justify-content:center;font-style:normal}.pk i svg{width:14px;height:14px}.pk u{text-decoration:none;font-size:9.5px;font-weight:900}.pk.on{border-color:var(--a);background:color-mix(in srgb,var(--a) 9%,transparent);color:var(--a)}
.rank{text-align:center;padding:10px;border-radius:16px;font-size:12px;font-weight:700;background:linear-gradient(135deg,var(--gold-bg),var(--surface));border:1.5px solid var(--gold-bd)}.rank b{font-size:17px;font-weight:900;color:#d97706}
.lb{background:var(--surface);border:1.5px solid var(--border);border-radius:16px;overflow:hidden}.lbh{display:flex;justify-content:space-between;align-items:center;padding:9px 12px;font-size:10px;font-weight:900;letter-spacing:1px;color:var(--faint)}.seg{display:flex;border:1.5px solid var(--border);border-radius:8px;overflow:hidden}.seg i{font-style:normal;padding:2px 8px;letter-spacing:0}.seg .on{background:#1e40af15;color:#1e40af}
.lr{display:flex;align-items:center;gap:10px;padding:9px 12px;border-top:1px solid var(--border)}.lr.you{background:var(--gold-bg)}.rk{width:16px;text-align:center;font-size:12px;font-weight:900;color:var(--muted)}.av{width:24px;height:24px;border-radius:50%;background:#7c3aed22;color:#7c3aed;font-size:10px;font-weight:900;display:flex;align-items:center;justify-content:center;flex:none}.nm{flex:1;min-width:0}.nm b{font-size:12px;font-weight:800}.nm small{font-size:10px;font-weight:700;color:var(--muted)}.nm em{font-style:normal;font-size:9px;font-weight:800;padding:1px 5px;border-radius:4px;background:#7c3aed1a;color:#7c3aed}.sc{font-size:12px;font-weight:900;font-variant-numeric:tabular-nums}
.tabs{display:flex;gap:6px}.tabs i{flex:1;text-align:center;font-style:normal;font-size:12px;font-weight:800;padding:8px 0;border-radius:12px;background:var(--border);color:var(--muted);border:1.5px solid var(--border)}.tabs .on{background:var(--surface);border-color:#7c3aed;color:#7c3aed}.sh2{font-size:10.5px;font-weight:900;letter-spacing:1.6px;color:var(--muted);border-left:4px solid #7c3aed;padding-left:7px;border-radius:2px}
.rc{position:relative;background:var(--surface);border:1.5px solid var(--border);border-radius:16px;padding:14px 12px 10px;overflow:hidden}.rch{display:flex;align-items:center;gap:8px;font-size:14px;font-weight:900}.rch .it{margin:0}.g2s{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin-top:8px}.stc{display:flex;gap:8px;align-items:flex-start;padding:7px;border-radius:8px}.stc>span{color:var(--a);margin-top:2px}.stc b{font-size:14px;font-weight:900;line-height:1.2;display:block}.stc small{font-size:10px;font-weight:700;color:var(--muted)}
.sg{display:grid;grid-template-columns:repeat(4,1fr);gap:12px 6px;background:var(--surface);border:1.5px solid var(--border);border-radius:16px;padding:14px 10px}.sg b{display:block;font-size:16px;font-weight:900;line-height:1.2}.sg small{font-size:8.5px;font-weight:800;letter-spacing:.6px;text-transform:uppercase;color:var(--muted)}.own{background:var(--surface);border:1.5px solid var(--border);border-radius:16px;padding:12px 10px}.own h6{margin:0 0 8px;font-size:10px;font-weight:900;letter-spacing:1.2px;color:var(--a)}.own .sg{border:0;padding:0;grid-template-columns:repeat(3,1fr)}.gone{font-size:11px;font-weight:700;color:var(--faint);text-align:center;padding:4px 8px}`;
