// GENERATED by packages/core/scripts/gen-mode-catalog.mjs from modes.json — DO NOT EDIT.
// Run `pnpm gen:modes` to regenerate. Edit packages/core/modes.json instead.
package com.wordocious.app

import androidx.compose.ui.graphics.Color

data class GenMode(
    val id: String,
    val dbKey: String?,
    val title: String,
    val shortTitle: String,
    val shareLabel: String,
    val desc: String,
    val accentHex: String,
    val glyph: String?,
    val romanNumeral: String?,
    val dailyEligible: Boolean,
) {
    val accent: Color get() = Color(("ff" + accentHex.removePrefix("#")).toLong(16))
    val accentInt: Int get() = ("ff" + accentHex.removePrefix("#")).toLong(16).toInt()
}

object ModeGen {
    val all: List<GenMode> = listOf(
        GenMode("practice", "DUEL", "Classic", "Classic", "Classic", "1 word, 6 tries", "#7c3aed", "C", null, true),
        GenMode("vs", null, "VS Battle", "VS", "VS Battle", "Real-time PvP", "#0d9488", null, null, false),
        GenMode("quordle", "QUORDLE", "QuadWord", "Quad", "QuadWord", "4 words at once", "#ec4899", "IV", "IV", true),
        GenMode("octordle", "OCTORDLE", "OctoWord", "Octo", "OctoWord", "8 boards, 13 tries", "#7e22ce", "VIII", "VIII", true),
        GenMode("sequence", "SEQUENCE", "Succession", "Succ.", "Succession", "4 words, one by one", "#2563eb", "S", null, true),
        GenMode("rescue", "RESCUE", "Deliverance", "Deliv.", "Deliverance", "4 prefilled boards", "#059669", "D", null, true),
        GenMode("six", "DUEL_6", "Six", "Six", "Classic Six", "6 letters, 7 tries", "#06b6d4", "6", null, true),
        GenMode("seven", "DUEL_7", "Seven", "Seven", "Classic Seven", "7 letters, 8 tries", "#84cc16", "7", null, true),
        GenMode("gauntlet", "GAUNTLET", "Gauntlet", "Gauntlet", "Gauntlet", "5 escalating stages", "#d97706", "G", null, true),
        GenMode("propernoundle", "PROPERNOUNDLE", "ProperNoundle", "Proper", "ProperNoundle", "Guess famous names", "#dc2626", "P", null, true),
    )
    fun byDbKey(k: String): GenMode? = all.firstOrNull { it.dbKey == k }
    fun byId(i: String): GenMode? = all.firstOrNull { it.id == i }
    val daily: List<GenMode> get() = all.filter { it.dailyEligible && it.dbKey != null }
}
