// Exports the app-wide profanity vocabulary (the SAME lists that screen
// usernames, ProperNoundle guesses and the Word of the Day) as exact words, so
// the offline lexicon builder applies one filter, not a second weaker copy.
//   tsx scripts/export-profanity-terms.ts  → scripts/data/profanity-exact.generated.txt
import { writeFileSync } from 'fs';
import { join } from 'path';
import { USERNAME_BLOCKED_SUBSTRINGS, USERNAME_BLOCKED_TOKENS } from '../packages/core/src/username';
import { WOTD_BLOCKLIST } from '../packages/core/src/wotd-blocklist';
const clean = (xs: readonly string[]) => [...new Set(xs.map((t) => t.toUpperCase()).filter((t) => /^[A-Z]+$/.test(t)))].sort();
const HEAD = '# GENERATED by scripts/export-profanity-terms.ts from packages/core. Do not hand-edit.\n';
// Slurs and strong profanity: never appear anywhere, never accepted.
const hard = clean([...USERNAME_BLOCKED_SUBSTRINGS, ...USERNAME_BLOCKED_TOKENS]);
// Taste list (anatomy, bodily, drugs, disease): real words a player may type,
// but never something we DEAL, feature or require.
const taste = clean(WOTD_BLOCKLIST).filter((t) => !hard.includes(t));
writeFileSync(join(__dirname, 'data', 'profanity-exact.generated.txt'), HEAD + hard.join('\n') + '\n');
writeFileSync(join(__dirname, 'data', 'taste-exact.generated.txt'), HEAD + taste.join('\n') + '\n');
console.log('exported', hard.length, 'hard terms,', taste.length, 'taste terms');
