/**
 * admin > Design > Sound Library (founder 10-06): every app sound grouped by game, the CURRENT sound (what ships,
 * tagged LIVE) next to its options, BMT + JP approve / reject / comment inline, "Approve all" per section and the
 * feedback Claude reads (public.sound_open_feedback). Modeled on the Art Library: the two-approver rule and the
 * request validation are art-review.ts's own; this file adds what is sound-specific. Pure (no React, no Supabase).
 *
 * Catalog: lib/admin/sound-catalog.json, generated by docs/design/brand/sounds/export-sound-catalog.py from the
 * Sound Lab (build-lab.py) and the shipped picks (make-sounds.py PICKS). Tables: docs/sql/20261010-sound-library.sql.
 *
 * A reviewer approves ONE candidate per event: approving B clears their earlier approve on A (a pick, not a vote
 * for every option). "Approve all" on a section approves what ships today (the LIVE candidate) for every event
 * the viewer hasn't decided yet.
 */
import catalogJson from './sound-catalog.json';
import {
  indexReviews, pendingReviewers, reviewStatus, SCOPE_RE,
  type ArtReview, type ArtReviewer, type ReviewDecision, type ReviewIndex,
} from './art-review';

export type SoundStatus = 'draft' | 'approved' | 'rejected' | 'shipped';
export type SoundOption = 'now' | 'a' | 'b' | 'c';

/** One candidate in the catalog: what ships ('now') or one of the lab's options. */
export interface SoundCandidate {
  opt: SoundOption;
  /** 'Now', 'A', 'B', 'C'. */
  letter: string;
  name: string;
  /** Grid sets: the set's full line ("Giggles: tiny synthesized voices"). */
  detail?: string;
  /** options/<key> clips (empty for 'now'). */
  keys?: string[];
  /** Playable URLs: one, or one per grid cell (empty = silent). */
  clips: string[];
  /** True on what ships today ('now'). */
  live: boolean;
  /** This option IS the shipped pick (same audio as Now). */
  same?: boolean;
  /** 'now' only: the shipped sound name(s) the event plays today (null = silent). */
  shipped?: string | string[] | null;
}

export interface SoundEvent {
  id: string;
  title: string;
  note: string;
  /** Grid events (hero laughs, Hubbub word lengths): the cell labels. */
  grid: string[] | null;
  colors?: string[] | null;
  candidates: SoundCandidate[];
}

export interface SoundSectionDef {
  id: string;
  title: string;
  blurb: string;
  events: SoundEvent[];
}

export interface SoundCatalog {
  note: string;
  targets: { jingle: number; ui: number };
  /** make-sounds.py PICKS as shipped: name -> options source + loudness target (number or 'match:<name>'). */
  picks: Record<string, { src: string; target: number | string }>;
  sections: SoundSectionDef[];
}

export const SOUND_CATALOG = catalogJson as unknown as SoundCatalog;

/** One row of public.sound_assets. */
export interface SoundAsset {
  id: string;
  section: string;
  section_title: string;
  event: string;
  event_title: string;
  option: SoundOption;
  option_name: string;
  clips: string[];
  shipped_name: string | null;
  live: boolean;
  status: SoundStatus;
  sort: number;
  decided_by?: string | null;
  decided_at?: string | null;
  updated_at?: string | null;
  note?: string | null;
}

/** sound_reviews rows have the art_reviews shape. */
export type SoundReview = ArtReview;
export type SoundReviewer = ArtReviewer;

export const soundId = (section: string, event: string, opt: string) => `${section}/${event}/${opt}`;

/** The catalog as sound_assets rows (what the SQL seed inserts), every status 'draft'. */
export function catalogAssets(catalog: SoundCatalog = SOUND_CATALOG): SoundAsset[] {
  const out: SoundAsset[] = [];
  let sort = 0;
  for (const s of catalog.sections) {
    for (const e of s.events) {
      for (const c of e.candidates) {
        sort += 1;
        const shipped = Array.isArray(c.shipped) ? c.shipped.join(',') : c.shipped ?? null;
        out.push({
          id: soundId(s.id, e.id, c.opt), section: s.id, section_title: s.title, event: e.id, event_title: e.title,
          option: c.opt, option_name: c.name, clips: c.keys ?? [], shipped_name: shipped, live: c.live,
          status: 'draft', sort,
        });
      }
    }
  }
  return out;
}

/** The candidate ids of one event (siblings share the section/event prefix). */
export function eventKeyOf(id: string): string {
  return id.slice(0, id.lastIndexOf('/'));
}

/* ------------------------------------------------------------------ the page */

export interface SoundCandidateView extends SoundCandidate {
  id: string;
  status: SoundStatus;
}

export interface SoundEventView extends Omit<SoundEvent, 'candidates'> {
  key: string;
  candidates: SoundCandidateView[];
  /** The candidate both reviewers approved (null while undecided). */
  picked: SoundCandidateView | null;
  /** The viewer's approved candidate in this event. */
  mine: string | null;
}

export interface SoundSectionCounts {
  events: number;
  /** Events where the viewer has not approved anything yet (or anyone still owes a call, for a non-reviewer). */
  toReview: number;
  /** Events with a pick both reviewers approved. */
  decided: number;
  /** Candidates the viewer rejected or commented on. */
  flaggedByMe: number;
}

export interface SoundSection extends Omit<SoundSectionDef, 'events'> {
  events: SoundEventView[];
  counts: SoundSectionCounts;
  /** Nothing left for the viewer: shown collapsed. */
  done: boolean;
}

export interface SoundReviewContext {
  index: ReviewIndex;
  reviewers: readonly SoundReviewer[];
  me: string | null;
}

const iReview = (ctx: SoundReviewContext) => !!ctx.me && ctx.reviewers.some((r) => r.profile_id === ctx.me);

/** True when the viewer (a reviewer) has approved some candidate of the event; for a non-reviewer, when every reviewer has. */
export function eventReviewed(ev: Pick<SoundEventView, 'candidates'>, ctx: SoundReviewContext): boolean {
  const who = iReview(ctx) ? [ctx.me!] : ctx.reviewers.map((r) => r.profile_id);
  // No approvers loaded (setup, or the list failed): nothing counts as reviewed.
  if (!who.length) return false;
  return who.every((id) => ev.candidates.some((c) => ctx.index.get(c.id)?.get(id)?.decision === 'approve'));
}

/**
 * The catalog grouped for the page: sections in lab order, each event's candidates (Now first) with the status
 * from the database (draft when the row isn't there yet), the decided pick and the viewer's own approve.
 */
export function groupSoundSections(
  statuses: ReadonlyMap<string, SoundStatus>,
  ctx: SoundReviewContext,
  catalog: SoundCatalog = SOUND_CATALOG,
): SoundSection[] {
  return catalog.sections.map((s) => {
    const events: SoundEventView[] = s.events.map((e) => {
      const candidates = e.candidates.map((c) => {
        const id = soundId(s.id, e.id, c.opt);
        return { ...c, id, status: statuses.get(id) ?? 'draft' };
      });
      const picked = candidates.find((c) => c.status === 'approved' || c.status === 'shipped') ?? null;
      const mine = ctx.me ? candidates.find((c) => ctx.index.get(c.id)?.get(ctx.me!)?.decision === 'approve')?.id ?? null : null;
      return { ...e, key: `${s.id}/${e.id}`, candidates, picked, mine };
    });
    const counts: SoundSectionCounts = { events: events.length, toReview: 0, decided: 0, flaggedByMe: 0 };
    for (const ev of events) {
      if (!eventReviewed(ev, ctx)) counts.toReview += 1;
      if (ev.picked) counts.decided += 1;
      for (const c of ev.candidates) {
        const d = ctx.me ? ctx.index.get(c.id)?.get(ctx.me)?.decision : undefined;
        if (d === 'reject' || d === 'changes') counts.flaggedByMe += 1;
      }
    }
    return { id: s.id, title: s.title, blurb: s.blurb, events, counts, done: counts.toReview === 0 };
  });
}

/** The line under a section title: "Picked for every event", "3 to review · waiting on JP" ... */
export function soundSectionSummary(s: Pick<SoundSection, 'events' | 'counts'>, ctx: SoundReviewContext): string {
  const { counts } = s;
  if (counts.events > 0 && counts.decided === counts.events) return 'Picked for every event';
  if (!ctx.reviewers.length) return `${counts.events} ${counts.events === 1 ? 'moment' : 'moments'}`;
  const waitingOn = ctx.reviewers.filter((r) => r.profile_id !== ctx.me
    && s.events.some((ev) => !ev.candidates.some((c) => ctx.index.get(c.id)?.get(r.profile_id)?.decision === 'approve')));
  const waiting = waitingOn.length ? ` · waiting on ${waitingOn.map((r) => r.short_name).join(' and ')}` : '';
  if (iReview(ctx) && counts.toReview === 0) {
    return `${counts.flaggedByMe ? `${counts.flaggedByMe} flagged by you` : 'All picked by you'}${waiting}`;
  }
  if (counts.toReview > 0) return `${counts.toReview} to review${waiting}`;
  return `Reviewed${waiting}`;
}

/**
 * "Approve all" for a section: the LIVE candidate of every event the viewer hasn't approved anything in yet,
 * skipping events where they rejected or commented on the live one. Non-reviewers get nothing.
 */
export function soundApproveAllPlan(s: Pick<SoundSection, 'events'>, ctx: SoundReviewContext): { ids: string[]; skipped: number } {
  if (!iReview(ctx)) return { ids: [], skipped: 0 };
  const ids: string[] = [];
  let skipped = 0;
  for (const ev of s.events) {
    if (ev.candidates.some((c) => ctx.index.get(c.id)?.get(ctx.me!)?.decision === 'approve')) continue;
    const live = ev.candidates.find((c) => c.live);
    if (!live || live.status === 'shipped') continue;
    const mine = ctx.index.get(live.id)?.get(ctx.me!)?.decision;
    if (mine === 'reject' || mine === 'changes') { skipped += 1; continue; }
    ids.push(live.id);
  }
  return { ids, skipped };
}

/**
 * One approve per event per reviewer: the viewer's other 'approve' rows in the same events as `ids` (cleared when
 * `ids` are approved). Rejects and comments on siblings stay.
 */
export function siblingApprovesToClear(
  ids: readonly string[],
  reviews: ReadonlyArray<Pick<SoundReview, 'asset_id' | 'reviewer_id' | 'decision'>>,
  me: string,
): string[] {
  const want = new Set(ids);
  const events = new Set(ids.map(eventKeyOf));
  return reviews
    .filter((r) => r.reviewer_id === me && r.decision === 'approve' && !want.has(r.asset_id) && events.has(eventKeyOf(r.asset_id)))
    .map((r) => r.asset_id);
}

/**
 * The optimistic (and server) version of a review landing: the viewer's rows for `ids` set to `decision` (an
 * approve also clears their approve on sibling candidates), and every touched candidate's status recomputed with
 * the two-approver rule (shipped is left alone). Returns the new reviews and status changes.
 */
export function applySoundReviews(
  statuses: ReadonlyMap<string, SoundStatus>,
  reviews: readonly SoundReview[],
  ids: readonly string[],
  me: string,
  decision: ReviewDecision,
  note: string | null,
  reviewers: readonly Pick<SoundReviewer, 'profile_id'>[],
  nowIso: string = new Date().toISOString(),
): { reviews: SoundReview[]; statuses: Map<string, SoundStatus>; cleared: string[] } {
  const want = new Set(ids);
  const cleared = decision === 'approve' ? siblingApprovesToClear(ids, reviews, me) : [];
  const clearSet = new Set(cleared);
  const prior = new Map(reviews.filter((r) => r.reviewer_id === me && want.has(r.asset_id)).map((r) => [r.asset_id, r]));
  const next = reviews.filter((r) => !(r.reviewer_id === me && (want.has(r.asset_id) || clearSet.has(r.asset_id))));
  for (const id of ids) {
    next.push({ asset_id: id, reviewer_id: me, decision, note, created_at: prior.get(id)?.created_at ?? nowIso, updated_at: nowIso });
  }
  const reviewerIds = reviewers.map((r) => r.profile_id);
  const touched = [...ids, ...cleared];
  const byAsset = new Map<string, SoundReview[]>();
  for (const r of next) if (touched.includes(r.asset_id)) byAsset.set(r.asset_id, [...(byAsset.get(r.asset_id) ?? []), r]);
  const out = new Map(statuses);
  for (const id of touched) {
    const cur = statuses.get(id) ?? 'draft';
    out.set(id, reviewStatus(cur, byAsset.get(id) ?? [], reviewerIds));
  }
  return { reviews: next, statuses: out, cleared };
}

/** Who still owes a call on a candidate (open candidates only), reusing the art rule. */
export function soundPendingReviewers(c: { id: string; status: SoundStatus }, ctx: SoundReviewContext): string[] {
  return pendingReviewers(c, ctx.index, ctx.reviewers);
}

export { indexReviews };

/** 'game:classic', 'event:app/intro' ... (the art scope shape). */
export function soundScope(kind: 'game' | 'event', id: string): string {
  const scope = `${kind}:${id}`;
  return SCOPE_RE.test(scope) ? scope : `${kind}:unknown`;
}

/** Label for a sound feedback scope: 'game:classic' -> 'Classic (whole game)'. */
export function soundScopeLabel(scope: string, catalog: SoundCatalog = SOUND_CATALOG): string {
  const [kind, id] = [scope.slice(0, scope.indexOf(':')), scope.slice(scope.indexOf(':') + 1)];
  if (kind === 'game') return `${catalog.sections.find((s) => s.id === id)?.title ?? id} (whole game)`;
  if (kind === 'event') {
    const [sid, eid] = id.split('/');
    const s = catalog.sections.find((x) => x.id === sid);
    const e = s?.events.find((x) => x.id === eid);
    return e ? `${s!.title} · ${e.title}` : id;
  }
  return scope;
}

/** A sound_assets / sound_reviews table that isn't there yet (the SQL isn't applied): Postgres or PostgREST codes. */
export function isMissingTable(error: { code?: string | null; message?: string | null } | null | undefined): boolean {
  if (!error) return false;
  return error.code === '42P01' || error.code === 'PGRST205' || /does not exist|schema cache/i.test(error.message ?? '');
}

export const SOUND_SETUP_NOTE = 'Reviews turn on once docs/sql/20261010-sound-library.sql is applied. Every sound already plays.';

/** Every candidate id of the event `id` belongs to (from the catalog; `id` itself included). */
export function siblingIds(id: string, catalog: SoundCatalog = SOUND_CATALOG): string[] {
  const key = eventKeyOf(id);
  const [sid, eid] = key.split('/');
  const ev = catalog.sections.find((s) => s.id === sid)?.events.find((e) => e.id === eid);
  return ev ? ev.candidates.map((c) => soundId(sid, eid, c.opt)) : [id];
}
